### ISSUE TITLE
Cannot exit back out of plugin

### ISSUE THREAD

**Issue by woody3000** [Alexqw/xbmc-gamepass#133]
Sometimes when I open up the plugin, I can't exit back out to the main xbmc.  Back, escape, everything I try reopens the plugin and it's back at the default screen with nothing selected.

This looks like the relevant part of the logs:
19:50:04 T:139835449120704   DEBUG: OnKey: percent (0x25) pressed, action is PreviousMenu
19:50:04 T:139835449120704   DEBUG: Activating window ID: 10025
19:50:04 T:139835449120704   DEBUG: ------ Window Deinit (/home/woody/.xbmc/addons/xbmc-gamepass-master/resources/skins/Default/720p/script-gamepass.xml) ------
19:50:04 T:139835449120704   DEBUG: ------ Window Init (MyVideoNav.xml) ------
19:50:04 T:139835449120704   DEBUG: CGUIMediaWindow::GetDirectory (plugin://plugin.video.nfl.gamepass/)
19:50:04 T:139835449120704   DEBUG:   ParentPath = [plugin://plugin.video.nfl.gamepass/]
19:50:04 T:139835449120704   DEBUG: StartScript - calling plugin NFL Game Pass('plugin://plugin.video.nfl.gamepass/','14','')
19:50:04 T:139835449120704   DEBUG: WaitOnScriptResult - waiting on the NFL Game Pass (id=20) plugin...
19:50:04 T:139833597925120  NOTICE: Thread LanguageInvoker start, auto delete: false
19:50:04 T:139833597925120    INFO: initializing python engine.
19:50:04 T:139833597925120   DEBUG: CPythonInvoker(20, /home/woody/.xbmc/addons/xbmc-gamepass-master/default.py): start processing
19:50:04 T:139833597925120  NOTICE: -->Python Interpreter Initialized<--

I can provide more detailed log files if needed.

**Comment by Alexqw** [comment]
@woody3000 Did this turn out to be the shortcut problem, or is this still a problem?

---Alex

**Comment by woody3000** [comment]
yes it did appear to be that shortcut problem.

**Comment by Alexqw** [comment]
@woody3000 Thanks for the update. :-)

**Comment by woody3000** [comment]
Thanks for providing and supporting this awesome plugin!

**Comment by justinrothaug** [comment]
I updated to the latest (2015.08.17 v0.7.4) and I still can't exit out of the Addon when using a shortcut (through Advanced Launcher to be precise). I did verify that my addons.XML file has the updated code:
<extension point="xbmc.python.script" library="default.py">

I'm using the CCM Helix skin if that matters, and exiting out of the plugin when entering through the Video Addons folder works fine.

Here's the Log if needed:
http://pastebin.com/raw.php?i=0ar6XEkA

**Comment by Alexqw** [comment]
@justinro HMm. Thanks for the info. I'll reopen this issue then.

---Alex

**Comment by BaumSchorle** [comment]
@justinro strange.... it's working on different skins on my setups, so I think it is something special with the Advanced Launcher approach.
Have you tried to delete and reconfigure the shortcut in Advanced Launcher?

**Comment by justinro** [comment]
Ah, okay I dove in further to this - Luckily it has nothing to do with Advanced Launcher, but a difference in how we are defining "shortcuts".

When launched from the 'Favorites' menu, I'm able to back out of the addon. 

But when I add a shortcut (keymap) in the keyboard.xml file to the addon and launch it using the shortcut, then I can't back out. The keymap I added looks like this:
<n mod="alt">xbmc.ActivateWindow(VideoFiles,plugin://plugin.video.nfl.gamepass)</n>

**Comment by BaumSchorle** [comment]
Awesome, good this is solved!
