### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by rslynn46** [Alexqw/xbmc-gamepass#151]
Hi Alex,

I have a small issue when using the confluence customizable mod skin. Is there anything I can do about this please?

http://postimg.org/gallery/22wx11h2w/

**Comment by kaileu** [comment]
Which Version of XBMC/Kodi you are using?

**Comment by rslynn46** [comment]
I'm using gotham. It only happens with the confluence mod skin. Must be a problem within the skin.

**Comment by Alexqw** [comment]
@rslynn46 Thanks for the bug report. Looking at the picture: that is... odd. I've never seen that one before.

I agree with you that it is likely a skin problem. So I'm going to close this issue, though feel free to reopen if you can reproduce it with Confluence on Helix or later.

---Alex
