### ISSUE TITLE
Invalid XML causes some games to fail

### ISSUE THREAD

**Issue by dahlSTROM** [Alexqw/xbmc-gamepass#157]
A few archived games do not play due to invalid XML syntax in the Coaches Film XML. An example is the Championship game between the Patriots and Colts. The addon will throw the good old 'bad jujumagumbo' error message because NFL uses invalid character entitles in their XML.
```
[plugin.video.nfl.gamepass-0.7.1]: Traceback (most recent call last):
                                              File "/home/emil/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 454, in onClick
                                                if gpr.check_for_coachestape(game_id, self.selected_season):
                                              File "/home/emil/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 120, in check_for_coachestape
                                                boxscore_dict = xmltodict.parse(boxscore)
                                              File "/home/emil/.kodi/addons/script.module.xmltodict/lib/xmltodict.py", line 248, in parse
                                                parser.Parse(xml_input, True)
                                            ExpatError: not well-formed (invalid token): line 3169, column 217

```

XML file from the game: http://neulionms-a.akamaihd.net/fs/nfl/nfl/edl/nflgr/2014/56500.xml (check line 3169, column 217)

The best solution is if NFL fixes their XML of course, but it might be a good idea to add checks that skips/corrects the syntax error.

**Comment by Alexqw** [comment]
Thanks for the bug report. Was this caused by the recent fix, or has this been going on for awhile?

The code has always been a bit too trusting of the XML supplied, so there is plenty of room for improvement there.

I'm quite busy with work for the time being, so it'd be great if someone with some spare time/energy could take a look at this. Otherwise, it likely won't be for awhile yet until I can dig into this.

---Alex

**Comment by dahlSTROM** [comment]
It's being going on for a while afaik, but it's not that big of a deal since it only affects a couple of games. I wish I could help you out, but my Python skills are unfortuanately atracious. :disappointed_relieved:

**Comment by kaileu** [comment]
This should fix it https://github.com/Alexqw/xbmc-gamepass/pull/162

**Comment by Alexqw** [comment]
Hey @dahlSTROM I merged @kaileu's fix and it should work now. Let me know if you run into any problems. :-)

---Alex
