### ISSUE TITLE
NFL Gamepass is down?

### ISSUE THREAD

**Issue by jrqiii** [Alexqw/xbmc-gamepass#158]
I know this isn't an issue with the Add-on but wanted to see if anyone else can't reach the Gamepass servers this morning?  I can't reach the website or launch this add-on or Windows Gamepass App.  Wanted to see if this is limited to US or everywhere.

**Comment by dahlSTROM** [comment]
I'd like to remind you that this is a developer area and not really the right board to ask these types of questions. It's working fine here (Sweden) FYI, but please avoid using GitHub for questions like this.

**Comment by jrqiii** [comment]
I know...thanks for the info.  Sorry
