### ISSUE TITLE
Missing urllib3 in Requests

### ISSUE THREAD

**Issue by msahlen** [Alexqw/xbmc-gamepass#160]
I have recently installed Helix 14.2 rc1. It was a clean install and since gamepass is one of the few plugins I use (great job BTW) i installed it at once. It was unfortunately unable to start, got the following error 

 12:14:18 T:1708790848  NOTICE: Thread LanguageInvoker start, auto delete: false
12:14:18 T:1971343360   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
12:14:18 T:1708790848  NOTICE: -->Python Interpreter Initialized<--
12:14:22 T:1708790848   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named 'requests.packages.urllib3'
                                            Traceback (most recent call last):
                                              File "/home/root/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 16, in <module>
                                                from resources.lib.pigskin import pigskin
                                              File "/home/root/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 14, in <module>
                                                import requests
                                              File "/home/root/.kodi/addons/script.module.requests/lib/requests/__init__.py", line 58, in <module>
                                                from . import utils
                                              File "/home/root/.kodi/addons/script.module.requests/lib/requests/utils.py", line 26, in <module>
                                                from .compat import parse_http_list as _parse_list_header
                                              File "/home/root/.kodi/addons/script.module.requests/lib/requests/compat.py", line 42, in <module>
                                                from .packages.urllib3.packages.ordered_dict import OrderedDict
                                              File "/home/root/.kodi/addons/script.module.requests/lib/requests/packages/__init__.py", line 83, in load_module
                                                raise ImportError("No module named '%s'" % (name,))
                                            ImportError: No module named 'requests.packages.urllib3'
                                            -->End of Python script error report<--
12:14:22 T:1971343360   ERROR: GetDirectory - Error getting plugin://plugin.video.nfl.gamepass/
12:14:22 T:1971343360   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nfl.gamepass/) failed
12:14:22 T:1708790848  NOTICE: Thread BackgroundLoader start, auto delete: false

Request seems to be installed correctly

root@wandboard-quad:~/.kodi/addons# ls
metadata.album.universal	    
script.common.plugin.cache   
script.module.xmltodict
service.subtitles.subscene
metadata.musicvideos.theaudiodb.com  
script.module.beautifulsoup 
service.subtitles.divxplanet	  
 service.subtitles.subscenter
packages	
script.module.mechanize	 
service.subtitles.napiprojekt
service.subtitles.supersubtitles
plugin.video.nfl.gamepass
script.module.parsedom
service.subtitles.opensubtitles
service.subtitles.undertexter
plugin.video.svtplay
script.module.requests
service.subtitles.podnapisi

**Comment by kaileu** [comment]
Hi, 
I think your request addon has a Problem ;-) so its not the Problem of the Gamepass addon.
A ugly hack would be to rename urllib3 to urllib2. But this should work ;-)

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment]
@msahlen Sorry for the late response. Indeed, as @kaileu mentioned, you are missing urllib3, which requests depends upon. It's a bit odd that it's missing, as the Requests kodi addon bundles urllib3 with it...

Did you install the gamepass addon from git or via Kodi?

If you installed via Kodi, then this is almost certainly a bug with the requests addon (and may have been fixed by now).

---Alex

**Comment by Alexqw** [comment]
Closing, as there is no response and I'm pretty sure this isn't our bug.

@msahlen Please feel free to reopen this if you still have this problem and think it's this addon's bug.

---Alex
