### ISSUE TITLE
Changes to activatewindow function Kodi 15.x (Isengard) break gamepass addon

### ISSUE THREAD

**Issue by Ghoschdi** [Alexqw/xbmc-gamepass#161]
The new 15.x version introduced a check if a modal dialog is open and if one is present, it rejects opening another window. (https://github.com/xbmc/xbmc/pull/6828)
Since busy dialog is modal, this breaks GP functionality.
> 17:11:20 T:1218171504   DEBUG: Activating window ID: 13000 
> 17:11:20 T:1218171504    INFO: Activate of window '13000' refused because there are active modal dialogs

Several changes have been made to Kodi due to this ticket: http://trac.kodi.tv/ticket/15960.

A quick fix is to make sure that the busydialog is closed when on changing to the main part 
`xbmc.executebuiltin('Dialog.Close(busydialog)')`@line:558

**Comment by Alexqw** [comment]
@Ghoschdi Thanks for the report and suggested fix. I applied your fix, but I am unable to test on Kodi 15. Though at very least it doesn't break anything on Kodi 14. ;-)

Let me know if this fixes it for you, if not, then please reopen.

---Alex

**Comment by Ghoschdi** [comment]
Tested and works on current Kodi 15 beta1.

**Comment by Alexqw** [comment]
Awesome. Thanks! :-)
