### ISSUE TITLE
Do a new release before pre-season starts in full-swing

### ISSUE THREAD

**Issue by anthonyettinger** [Alexqw/xbmc-gamepass#169]
Is there a repo that has latest updates for this plugin?

**Comment by Alexqw** [comment]
@anthonyettinger No, but master is only 3 commits ahead of the previous tagged release. And only one is a bug fix. I never tested the bugfix, since I didn't have Isengard at the time, so I don't know its severity.

I will make a release sometime this week with other outstanding PRs included.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw We should to add the 2015 season for the shows, before the new release

As you can see in this log, they have the new shows already in the xml we receive after login.

http://pastebin.com/BDjDPkhZ

**Comment by kaileu** [comment]
https://github.com/Alexqw/xbmc-gamepass/pull/174

**Comment by BaumSchorle** [comment]
@kaileu Thank you very much for the fast update!

**Comment by Alexqw** [comment]
@BaumSchorle Thanks for pointing out the show codes; I forgot about those. And I've merge @kaileu's ridiculously fast PR, so we're all set there. ;-)

I've told the Kodi guys to cancel my request to update in the main repo. We need to resolve this Android problem (#173) before we update there, as a bunch of users are on Amazon Fires. I wonder how spotimc gets around the problem.

Any thoughts on what else should be resolved before a release? I was hoping to get one out before the first weekend of pre-season games.

---Alex

**Comment by chovy** [comment]
I'm running kodi on a mac and firetv. let me know if you want me to test anything.

**Comment by BaumSchorle** [comment]
@anthonyettinger can you please download the latest updates from https://github.com/Alexqw/xbmc-gamepass/archive/master.zip and install it on your firetv box and test if everything is working?

A user is reporting in #173 about issues on firetv and I just provided a possible fix for this

**Comment by chovy** [comment]
@BaumSchorle everything works fine on FireTV, but nothing works on Mac now.

Mac logs
http://xbmclogs.com/prme7yhvs

On FireTV I tried 2015 hall of fame game, 2014 week 7 game and also 2014 redzone archives....all work on FireTV although there are some long delays in loading things (w/o spinner present).

On my mac I couldn't get anything to play. It would stop as soon as I got the spinner. Spinner would hang for a few seconds then go away when I tried to play.

**Comment by BaumSchorle** [comment]
@chovy This is strange, looks like the addon is doing everything fine but then kodi runs into a timeout when opening the stream. Maybe a network issue!? Are you behind some kind of proxy on your mac?

**Comment by chovy** [comment]
Nope....everything else works fine in Kodi for me.

**Comment by BaumSchorle** [comment]
@chovy does this work with the version in the official repo? Did it work before my fix? Because my fix didn't touch any of this logic, it was just about the skin/font logic.

**Comment by BaumSchorle** [comment]
@Alexqw What do you think about adding the new release to the official repo?

**Comment by Alexqw** [comment]
@BaumSchorle I was hoping we could get the US edition working, but it doesn't look like that'll be an easy fix. I'll do a 0.7.3 release tonight and hopefully the Kodi devs will pull it quickly. The rest of the work can go into an 0.8.0 release.

**Comment by chovy** [comment]
@BaumSchorle on official repo only archived games worked. Nothing else I tried, like RedZone archives worked.

**Comment by Alexqw** [comment]
Submitted 0.7.4. Hopefully this one makes it through.

**Comment by Alexqw** [comment]
0.7.4 was just accepted into the repo.

Closing.

---Alex
