### ISSUE TITLE
Some mumbo jumbo just went down.

### ISSUE THREAD

**Issue by chovy** [Alexqw/xbmc-gamepass#170]
https://www.dropbox.com/s/idwwp9zl1v2yw7q/Screenshot%202015-08-08%2018.02.36.png?dl=0

Got this when I try to load Redzone archives from last year.

http://xbmclogs.com/pr4jqvnuc

**Comment by kaileu** [comment]
Please describe what you wanted to do that causes the error and post log file with activated debug functions.


Mit freundlichen Grüßen
Kai Leutner

Am 09.08.2015 um 03:03 schrieb Anthony Ettinger <notifications@github.com<mailto:notifications@github.com>>:


https://www.dropbox.com/s/idwwp9zl1v2yw7q/Screenshot%202015-08-08%2018.02.36.png?dl=0

**Comment by chovy** [comment]
Did I not just say that?

https://www.dropbox.com/s/idwwp9zl1v2yw7q/Screenshot%202015-08-08%2018.02.36.png?dl=0

Got this when I try to load Redzone archives from last year.

http://xbmclogs.com/pr4jqvnuc

**Comment by kaileu** [comment]
@chovy sry in my mail client i didn't saw the log link ;-)

It's the same error as in https://github.com/Alexqw/xbmc-gamepass/issues/167  You have to wait a bit or merge my fixes as in issue 167.

**Comment by Alexqw** [comment]
@chovy @kaileu Yeah, life has been crazy busy the last 2 months. I'll do my best this week to test out the outstanding PRs, get them merged, and post a release to Kodi's addons.

---Alex

**Comment by chovy** [comment]
Thanks Alex....excellent work by the way. If we can fix the bugs (I'll try to help where I can) then this will be much welcomed.

**Comment by Alexqw** [comment]
Hey @chovy, I merged @kaileu's fix and it should resolve this problem. I've tested it, and it works for me.

Let me know if you run into any more problems, and thanks for taking the time to report this bug. :-)

---Alex

**Comment by chovy** [comment]
Is it in the official Kodi repo?

**Comment by chovy** [comment]
I don't see any new releases.

https://github.com/Alexqw/xbmc-gamepass/releases

**Comment by Alexqw** [comment]
@chovy Indeed, there is no new release yet. The last few patches were a bit more aggressive, so I'm waiting a few days to make sure there's no breakage before tagging it as a release.

You will note that I left the other issue you filed as open, #169; the one in which you ask for a new release. That one will be closed once there is a new release.

---Alex

**Comment by rslynn46** [comment]
Hi Alex,

So for now do we just install the zip from Git Hub to solve the small issues?

**Comment by Alexqw** [comment]
@rslynn46 That's your decision. You can either

1) Wait 1 or 2 days for me to release to the kodi repo
2) git clone this repo into your addons directory
3) download the .zip file (right side of main page of repo) and use Kodi's "install from .zip file" option for addons.

Whichever suits your needs the best.

---Alex
