### ISSUE TITLE
NFL Rewind is gone.  NFL "Gamepass" for all.

### ISSUE THREAD

**Issue by sdalberg** [Alexqw/xbmc-gamepass#171]
NFL Rewind has been rebranded to NFL Gamepass in the US, but the features are the same as NFL Rewind more or less (no live games).  Plugin hasn't been working since the change unless I'm missing something.

Anyone in the US get it to work?

Edit by Alex
---
So, removing GameRewind has a few tasks:
- [x] Determine if GamePass US Edition behaves the same as International Edition
  - [x] If so: remove GameRewind from the skin (#186)
  - [ ] If so: remove GameRewind from the settings/code
- [x] Redo Icon (#176)
- [ ] Handle blackouts (which also affects Game Pass International in Canada, Ireland, and the UK)
- [x] Verify which shows GamePass US supports (GameRewind only had NFL GameDay and Top 100 Players)
- [x] Update Readme to reflect new US Edition

**Comment by chovy** [comment]
I am in the US but I have the international version of NFL GP.

I hear the US version doesn't have live games. I would imagine its just disabled in the official UI.

**Comment by Alexqw** [comment]
@sdalberg Likely only a few changes are needed, but none of the devs (that I'm aware of) are in the US, thus making development for the US service quite difficult.

What if you set the "Subscription Type" (in settings) to Game Pass? That would be wonderful if it worked...

---Alex

**Comment by sdalberg** [comment]
Logs: http://pastebin.com/BDjDPkhZ

important bit possibly:  
14:06:40 1644386.250000 T:1675621440   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning

**Comment by sdalberg** [comment]
This doesn't look to be platform specific.  I have tried it on Openelec (RPi2 and x86/32 bit) and OSX.

**Comment by Alexqw** [comment]
@sdalberg That SSL issue seems to be a problem with the Requests module (which the addon uses) while redirecting and using < Python 2.7.9.

I also see in the logs that you aren't using a username. You need to have an account with Game Pass and supply a username and a password in order to login.

---Alex

**Comment by sdalberg** [comment]
I have configured creds for both rewind (username) and Gamepass (Email Address).  Neither works and both produce this error.

**Comment by Alexqw** [comment]
@sdalberg So there's likely two issues here (though it's not for certain): 1) SSL issues with Requests/python 2) GameRewind retirement and our GamePass code doesn't work for US GamePass.

Can you upload a debug log for your OS X box? With that Python version (assuming Kodi is using system Python), it shouldn't have the same SSL issue as your OpenELEC. Then it'll be easier to tease things apart.

---Alex

**Comment by sdalberg** [comment]
http://pastebin.com/kV4uN0wf

2.7.10 is the python version

**Comment by dahlSTROM** [comment]
Maybe we should try logging in using the servlets URL instead?
```python
    def login_to_account(self, username, password):
        """Blindly authenticate to Game Pass/Rewind. Use
        check_for_subscription() to determine success.
        """
        url = self.base_url + '/secure/nfllogin'
        post_data = {
            'username': username,
            'password': password,
        }
        self.make_request(url=url, method='post', payload=post_data)
```

It's what the Android/iPhone apps are using to authenticate. It also responds with XML data we can use for check_for_subscription().
```xml
<?xml version="1.0" encoding="UTF-8"?>
<result>
	
		<code>noproductaccess</code>
	
	
		<data>
			
				<userName><![CDATA[*******]></userName>
			
				<givenName><![CDATA[******]]></givenName>
			
		</data>
	
</result>
```

**Comment by BaumSchorle** [comment]
@dahlSTROM This may be a good approach and another step closer to emulating the behaviour of the iphone app.
Do you want to give it a shot, as it seems you already looked into this?

**Comment by Alexqw** [comment]
@sdalberg Can you update to the latest git revision and give it another try? I just merged @dahlSTROM's patch to make the login process use the new login servers.

Also, it wouldn't hurt if you deleted kodi's temp folder (~/.kodi/temp on Linux and OS X) just in case. It shouldn't matter, but it'll help guarantee you aren't getting a weird cached response.

---Alex

**Comment by sdalberg** [comment]
with this latest version I get it working on the OSX side of things mostly (playing the actual games is hit and miss, but I haven't poked at that too much yet, but on the Openelec boxes I'm getting the following: http://pastebin.com/07XUB1zZ

Sorry this didn't start at the beginning but it was rolling past my scrollback.  it was in a continual retry look until I broke it out.

**Comment by BaumSchorle** [comment]
@sdalberg looks like this is an issue with your user credentials. It says login failed an 'no username' detected. Please check your settings

**Comment by sdalberg** [comment]
the credentials are set, checked it twice.

On 13 August 2015 at 10:41, BaumSchorle <notifications@github.com> wrote:

> @sdalberg <https://github.com/sdalberg> looks like this is an issue with
> your user credentials. It says login failed an 'no username' detected.
> Please check your settings
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexqw/xbmc-gamepass/issues/171#issuecomment-130775824>
> .
>



-- 
Steve

**Comment by BaumSchorle** [comment]
Hm... The only thing that comes to my mind to solve this: completely uninstall this addon, clear the cache, make sure the settings are deleted and them reinstall.

However it could be something completely different, maybe the us login works different.
Without a developer located in the us who can dig into this it's goingbto be difficult to solve this

**Comment by Alexqw** [comment]
@sdalberg If the latest code isn't working, then it's going to require more digging from your side. We need to see which login server that Game Pass US's web interface is talking to and what parameters its (likely) POSTing to the server.

The best tools to start with is Firefox's Firebug addon or Chrome's DevTools.

---Alex

**Comment by MHorner666** [comment]
Hello, I'm trying to access the US version of Gamepass from within the US and experiencing the same issue of failed credentials. I'm trying to use Gamepass in Kodi sideloaded onto my Amazon Fire Stick. I've got a *little* experience with coding, and would be more than happy to try to dig into the credential issue, but might need a gentle push towards which areas I should attempt to look at.

**Comment by Alexqw** [comment]
@MHorner666 Excellent. First off, make sure you're using the latest addon code from git.

Then I recommend using Firebug with Firefox or Chrome's DevTools. On a laptop/desktop, start the tools, and login to GamePass in the web browser. There's a network tab that will show all assets loaded (images, CSS, JS, HTML, and information sent (POSTed) to their servers). What we're interested in is a page likely called "login", and the parameters sent to this page.

We need to know what is that page's URL, and what parameters are used, and what the content of those parameters are (unless of course it's your password ;-). And if there's a response from the server, what that response is.

---Alex

**Comment by MHorner666** [comment]
Thanks for the quick response. So an uninstall and re-install seems to have done the trick. What's interesting is that I have access to live NFL network, which I thought was not possible with a domestic US description (I'm not running through a DNS service or VPN).

I'll be glad to look into US-based problems in the future, should they arise. Thanks for the work to produce the add-on!

**Comment by BaumSchorle** [comment]
Can anyone check the features of the official GamePass in the US? Is Nfl Network Live included?

They provide a new flag in the login response (isDomestic). Maybe we need to make sure that we are checking this flag for the features!

**Comment by Alexqw** [comment]
@BaumSchorle Yup, I think the isDomestic flag will be needed to handle the blackout logic.

I looked at a google cached version of the GamePass Domestic website (I think "Game Pass Domestic" is their name for the US edition) and they don't list the actual shows provided. They just say that you have access to the NFL's shows. So, I think someone with Game Pass Domestic will need to go into the web interface and list what shows are available.

@MHorner666 Glad it's working. :-) It may have just been that you needed the latest code and some caches to expire. :-D

@sdalberg Does it work for you with the latest code now?

**Comment by sdalberg** [comment]
Working well on OSX, not on Openelec, which seems to be related to the following difference.  On the working instance:
11:40:38 T:4640133120  NOTICE: [pigskin]: Request URL: http://gamepass.nfl.com/nflgp/servlets/simpleconsole
11:40:38 T:4640133120  NOTICE: [pigskin]: Headers: None
11:40:39 T:4640133120  NOTICE: [pigskin]: Response code: 200
11:40:39 T:4640133120  NOTICE: [pigskin]: Response: <?xml version="1.0" encoding="UTF-8"?>

On the non-working:
11:36:49 507.950073 T:1218442304  NOTICE: [pigskin]: Request URL: https://gamepass.nfl.com/nflgp/secure/nfllogin
11:36:49 507.950378 T:1218442304  NOTICE: [pigskin]: Headers: None
11:36:50 508.009705 T:1207956544   ERROR: /storage/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
11:36:50 508.042389 T:1233122368  NOTICE: [pigskin]: Response code: 200

so my Openelec box (running latest) isn't trying the simpleconsole login.  Is there a cache I can manually clear?  I've completely removed the addon directory and installed from today's zip.

**Comment by Alexqw** [comment]
@sdalberg So, our addon cheats a bit by checking if it has access to Game Pass before trying to authenticate. If there's already access, then it just skips over the authentication process. That's likely what you're seeing there, since you can't login through the simpleconsole check in the first one.

First off, you need to delete the ~/.kodi/temp/ directory, which contains cached information, including the cookie.

If it's still skipping the authorize step, then I /think/ (it's been awhile) to get around this issue is to open the Game Pass web interface on the system that is already authenticated, and choose logout. That should deauthenticate the machine as a whole. Then you /should/ see the full login procedure.

I just want to make sure that OS X working is authentic, and not a byproduct of some dangling credentials from a web session. If OS X actually works, 100%, all the way through, that is /great/ and then we're just left with that damn SSL issue on some platforms (which I have one idea left on how to fix).

What version of python is your OpenELEC box running?

---Alex

**Comment by sdalberg** [comment]
iirc the python version on openelec is 2.7.3, but I will verify when I get
home.

On 14 August 2015 at 12:40, Alex Waite <notifications@github.com> wrote:

> @sdalberg <https://github.com/sdalberg> So, our addon cheats a bit by
> checking if it has access to Game Pass before trying to authenticate. If
> there's already access, then it just skips over the authentication process.
> That's likely what you're seeing there, since you can't login through the
> simpleconsole check in the first one.
>
> First off, you need to delete the ~/.kodi/temp/ directory, which contains
> cached information, including the cookie.
>
> If it's still skipping the authorize step, then I /think/ (it's been
> awhile) to get around this issue is to open the Game Pass web interface on
> the system that is already authenticated, and choose logout. That should
> deauthenticate the machine as a whole. Then you /should/ see the full login
> procedure.
>
> I just want to make sure that OS X working is authentic, and not a
> byproduct of some dangling credentials from a web session. If OS X actually
> works, 100%, all the way through, that is /great/ and then we're just left
> with that damn SSL issue on some platforms (which I have one idea left on
> how to fix).
>
> What version of python is your OpenELEC box running?
>
> ---Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexqw/xbmc-gamepass/issues/171#issuecomment-131216946>
> .
>



-- 
Steve

**Comment by Alexqw** [comment]
It's worth noting that GamePass is having a lot of growing pains ATM. https://twitter.com/NFLGamePass/with_replies

I'm not saying that this addon isn't at fault, but we should try to keep it in mind so we aren't chasing dead-ends.

**Comment by Alexqw** [comment]
@sdalberg Just to confirm, the latest code works for you on OS X? If so, that's /great/, and we can start ripping out old Rewind code/configs.

The OpenELEC issue is almost certainly the SSL cert problem in #183 

---Alex

**Comment by sdalberg** [comment]
agreed, looks good for me on osx and openelec (x64 -32bit), only arm is
being difficult.

On 16 August 2015 at 07:14, Alex Waite <notifications@github.com> wrote:

> @sdalberg <https://github.com/sdalberg> Just to confirm, the latest code
> works for you on OS X? If so, that's /great/, and we can start ripping out
> old Rewind code/configs.
>
> The OpenELEC issue is almost certainly the SSL cert problem in #183
> <https://github.com/Alexqw/xbmc-gamepass/issues/183>
>
> ---Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexqw/xbmc-gamepass/issues/171#issuecomment-131554803>
> .
>



-- 
Steve

**Comment by Alexqw** [comment]
@sdalberg Great. Do all of the shows work? Previously, the Game Rewind subscription didn't get many of the shows. Can you (or someone) test all of them, and report which (if any) fail?

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw Handling BlackOuts should be pretty easy, if there is a 'isGPDomestic' flag we should disable all currently running games, like if they have not started.

**Comment by Alexqw** [comment]
@BaumSchorle That's assuming they allow the user to login. With GameRewind, the entire service was disabled, not just games. So we need to see if they continue with that, or just disable games. Etc, etc.

---Alex

**Comment by Alexqw** [comment]
** crickets ** .... can any Game Pass Domestic users (or someone in the US, get a Game Pass Domestic free trial) provide some info about which shows are offered?

---Alex

**Comment by sdalberg** [comment]
A Football Life
America's Game
Hard Knocks
Sound FX
Super Bowl Archives

**Comment by kaileu** [comment]
Could you turn on debug mode and post a logfile?
Because of the new show (americas game) we need the id to hopefully integrate this show 😊

Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment]
@sdalberg Excellent, thanks. :-)

Can you confirm that there is no "NFL Game Day"? It was offered for Rewind users.

---Alex

**Comment by bondy2108** [comment]
Hey Alexqw
Im having some issues with the app on my firestick(Kodi running)
The program never launches and just comes up with Epic Failure (some bad jujumagumbo just went down)
Any advice or help would be great mate Cheers

**Comment by Alexqw** [comment]
Closing. First week came and went without complaints from Domestic Users. Any future problems/needed-features can go into their own issues.

---Alex
