### ISSUE TITLE
"Some bad jujumagumbo just went down." after updating to 0.72

### ISSUE THREAD

**Issue by Displayel** [Alexqw/xbmc-gamepass#173]
Hi, 
guys i just updated to the new version 0.72 but now when i open the gamepass that error in the thread title is showing up and it won´t work anymore, i tried to restart kodi and did again but the same error, i´m using a firetv with Kodi Isengard 15.1 RC.

sorry i have no idea how to post the bug report or where i should look to get it

Cheers Alex

**Comment by Alexqw** [comment]
@Displayel Thanks for opening a ticket.

Please enable "Debugging" in the addon's settings.

Then please follow these instructions: http://kodi.wiki/view/Log_file

@BaumSchorle I think his issue is related to the recent font work. It works fine for me on Helix; are you running Isengard or Helix?

---Alex

**Comment by Displayel** [comment]
Hi,
thanks for that here is the log 

http://xbmclogs.com/pguaa52gc

**Comment by BaumSchorle** [comment]
@Alexqw I am running Isengard but this looks like something Android specific. Looks like Android is preventing our Addon from updating the XML-Files.

This looks like the copying confluence from protected installation directory to the userdata folder has not worked right. It is still trying to work in the protected directory.

File "/home/jenkins/workspace/Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-17/lib/python2.6/shutil.py", line 66, in copymode
                                            OSError: [Errno 1] Operation not permitted: '/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/skin.confluence/720p/Font.xml-skinutilsbackup'

@Displayel Can you please try to restart kodi. Does this error still occur?

**Comment by Alexqw** [comment]
@BaumSchorle It looks like spotimc doesn't support either iOS or Android. I don't know if that's due to spotify lib issues or the font stuff.

**Comment by BaumSchorle** [comment]
@Alexqw This is what I think happened:

If you are using Confluence and starting GamePass Addon for the first time, the message pops that some additional stuff has to be installed and you need to restart kodi. What acutally happens is that Cofluence skin is copied from "standard installation" folder to userdata folder.
This has to be done because an addon is not allowed to edit files in the kodi installation folder.

So if you do not restart Kodi after first start with Confluence, you will always run into this error. Because you are still running with Confluence from installation folder and not the copied Confluence skin in the userdata folder.

Maybe we need an extra check and stop the addon from starting as long as Kodi was not restarted.

So as long as Skins are supported on Android, then this should work.

This behaviour should occur on ALL platforms, if I am right

**Comment by Alexqw** [comment]
@BaumSchorle Interesting. I did run into that message, and I tested Confluence first, and did restart Kodi. So I may have accidentally done the proper dance the first time around. ;-)

Yeah, we do need to have a popup to educate users accordingly.

@Displayel Can you try running this with Confluence, then restart Kodi and try again? Also, as for the buffering issue, all I can recommend is lowering the bitrate and checking the hardware acceleration settings.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw This can be easily tested: 

* delete confluence skin in userdata folder
* select Confluence skin as your skin
* start gamePass addon
* do not restart kodi and try to use GamePass addon

I am currently at work so can't test right now, but will check as soon as I am at home.

Adding a check should be easy, as far as I know the new libraries provide a check whether the skin files are writable.

**Comment by Alexqw** [comment]
@BaumSchorle Yeah, I'm busy ATM, so I'll leave it for you to test tonight. ;-)

Thanks for working on this.

---Alex

**Comment by Displayel** [comment]
hey guys,
thanks for your support, so i already tried a restart and then tested again yesterday but with no success, the error stayed the same, since the firmware on my firetv is over a certain version i´m not able to root the firetv so i´m not sure how i can delete anything from the root directory.

[quote]@Displayel Can you try running this with Confluence, then restart Kodi and try again? Also, as for the buffering issue, all I can recommend is lowering the bitrate and checking the hardware acceleration settings.[/quote]

so i think i already did this step yesterday, Confluence is my standard skin, its always on, i just asked about the buffer problems because they occur no matter which bitrate i chose and when i have gamepass running over my browser i don´t have this problems, which accleration would you suggest, MediaCodec or libstagefright ? 

thanks again for your support

**Comment by BaumSchorle** [comment]
I just tested this on my Android tablet (Android 4.4.2 wih Kodi 15.0 from PlayStore) and it worked. As @Displayel mentioned the first time i got the error, but after restarting it works like expected.

So this may be an issue with fireTv. I have no fireTv to test this. But on my Android Tablet it's working.

**Comment by BaumSchorle** [comment]
Seems like this is happen to some Android installations, I found a few bug reports on the web about this. 

Interesting is that the App was able to copy the confluence skin to the addons folder, but now is not able to create a backup of the font.xml in this folder: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/skin.confluence/720p/

@Displayel Can you please try to install any random addon from the official repo? Just to check if this is a problem with your kodi installation!?

Thanks.

**Comment by Displayel** [comment]
hi,
well kind of embarrassing but i don´t how i would do this sorry, i´m still kind of new to the kodi family, i mostly work with addons only because i don´t want to put to much garbage on my FireTV, can you tell me how to do it and i will do right away

Alex

**Comment by BaumSchorle** [comment]
@Displayel don't worry, we all were new one day :)

You simply go to Video --> Addons --> Get More --> Choose one from the list --> Install

I just want to find out if this is a general problem with writing to the addon directory.

After a successfull installation you can go to Video --> Addons --> choose the new Addon --> context Menu --> Uninstall

**Comment by Displayel** [comment]
ok thanks that was easy :), so installed the "arte.tv" addon and then the live tv option, works just fine

**Comment by BaumSchorle** [comment]
Damn... so I need to dig deeper! I will try to find a solution! Let you know if there is something to test!

**Comment by Displayel** [comment]
thanks for your effort, i really appreciate it, kind of strange that no one else has reported this issue so far, maybe no one runs kodi on a FireTV over here

**Comment by BaumSchorle** [comment]
@Displayel which version of Kodi are you running?

**Comment by BaumSchorle** [comment]
@Displayel I have provided a possible solution for this, can you please download the latest update and test this?

**Comment by Displayel** [comment]
well, whatever you did, it works !!! thanks, that error in the thread title shows up one more time when i press on nfl network live, but when i press it again right away it works...Thanks, youre the man !!!

**Comment by BaumSchorle** [comment]
@Displayel That's good news. Glad it helped.

If this error when clicking on nfl network live continues to appear you can provide us the logs, so we can look into it. Please activate the debugging option in the addon-settings.

**Comment by BaumSchorle** [comment]
@Displayel I think we can close this issue, as it is fixed! If you continue to have problems with NFL-Network live stream, please open a new issue and provide debug-log.

Thanks!

**Comment by dimennad** [comment]
@BaumSchorle I just purchased my android box and am also an amateur so bear with me. It's been wonderful so far but i'm having the same issue as @Displayel . I get the same message and have found your solution, but I have no idea how to download it onto my android box. I'm currently using a tablet, thanks in advance!

**Comment by Alexqw** [comment]
@dimennad Are you running the latest version (0.8.0)? This bug report is for a problem that no longer exists in the code. "Bad jujumagumbo" is a generic error message when an error that we don't expect happens.

Please update to the latest version. If you still have a problem, please turn on debugging (in both the addon and kodi), open a new issue, and provide a log.

---Alex
