### ISSUE TITLE
New Icon Needed - Game Pass Only

### ISSUE THREAD

**Issue by Alexqw** [Alexqw/xbmc-gamepass#176]
Now that Game Rewind has been retired, we need a new icon for Game Pass — all by itself. My graphic abilities are... let's say... insufficient. It'd be great if someone more graphically inclined would put something together.

My icon requirements are:
* look sexy as hell ;-)
* all images/text/logos used to create the icon must be Free (as in Freedom)
  - if any are used, please provide license info so it can be added to the License file
* cannot use the NFL logo
* cannot imply that this is an official application (for example, by using the above-mentioned NFL logo)

Let me know if you have any questions!

---Alex

**Comment by eriksoderblom** [comment]
Made a quick icon, what do you think?
![GP Logo](http://i.imgur.com/VrmHN5a.png)

**Comment by BaumSchorle** [comment]
Nice start... Do you think you can give it some kind of glossy 3D look? Hope you know what I mean ;)

**Comment by Alexqw** [comment]
@eriksoderblom And let the bike shedding begin. ;-)

I like it, but I do feel like the text is a bit dwarfed by the logo. Just my 2 cents.

---Alex

**Comment by frostyon420** [comment]
![mod-logo](https://cloud.githubusercontent.com/assets/5342680/9264514/321137ee-41dc-11e5-82a1-d018a3408ee3.png)

**Comment by eriksoderblom** [comment]
Made some changes to mine
![GP Logo](http://i.imgur.com/ccwCac5.png)

**Comment by frostyon420** [comment]
i like the rounded edges. Not big on the word gamepass though. Wish the font color was gold, I think an abbreviation is the better way to go, rather then the whole spelling. but i know nothing lol

**Comment by eriksoderblom** [comment]
@frostyon420 Do you mean something like this?
![GP Logo](http://i.imgur.com/0fy5vy3.png)
![GP Logo](http://i.imgur.com/3bAFdoO.png)

The NFL is using gold logos this year to celebrate SB 50, and personally I don't like it.
I'd rather have the white text on blue background
Like this
![GP Logo](http://i.imgur.com/M5IUDmk.png)

**Comment by frostyon420** [comment]
exactly, what i mean :)
ive been playing with your template
![icongpericmod](https://cloud.githubusercontent.com/assets/5342680/9265167/3b015d9a-41e4-11e5-986a-72162cb4d725.png)

**Comment by BaumSchorle** [comment]
Guys this looks pretty cool... :+1: 

I like this approach:
![GP Logo](http://i.imgur.com/M5IUDmk.png)

But this is also pretty cool looking, but I don't really like the gold too much bling bling: :joy: 
![blackngoldericmod](https://cloud.githubusercontent.com/assets/5342680/9265356/dcb0926c-41e6-11e5-8909-bb26e5f9a937.png)

**Comment by Alexqw** [comment]
/Nice/

I definitely prefer the cleaner look. Most of the textures come across as too busy for me (though the football background one is pretty cool). These three are my favorites thus far.

![GP Logo](http://i.imgur.com/M5IUDmk.png)
![GP Logo](http://i.imgur.com/3bAFdoO.png)
![blackngoldericmod](https://cloud.githubusercontent.com/assets/5342680/9265356/dcb0926c-41e6-11e5-8909-bb26e5f9a937.png)

I'm not a huge fan of the gold, but I can definitely see how some people would like the look (as an aside, it would be /really/ cool if we could sometime figure out how to hook into Kodi's fanart stuff and allow users to set their own fanart and possibly icons [#153]; then we could provide many options). I think it's all personal preference.

Anyone else have thoughts, opinions, votes?

---Alex

**Comment by BaumSchorle** [comment]
Just a little thing that came to mind, we should keep it classy and restrained as some people have this icons integrated into their skins somewhere.

I vote for this one:
![GP Logo](http://i.imgur.com/M5IUDmk.png)

**Comment by frostyon420** [comment]
![gpmodicon](https://cloud.githubusercontent.com/assets/5342680/9288115/43dbdc9e-42eb-11e5-8129-bf433c32689c.png)

**Comment by Alexqw** [comment]
@eriksoderblom So, I think we've decided on this one. Can you provide a slightly higher res version (512x512?)? The Amber skin, for example, uses really large addon icons, and it becomes quite pixelated. 

![GP Logo](http://i.imgur.com/M5IUDmk.png)

@frostyon420 Thanks for your submissions as well. We can definitely use some of your good work when we get user-selected fanart/icons figured out. :-)

---Alex

**Comment by eriksoderblom** [comment]
@Alexqw I could provide a 512x512 version of the icon, but Kodi wiki states that icons should be 256x256, so should we ignore the wiki?

And i was thinking that it might look better with square corners since some skins use square frames around the icons.

**Comment by Alexqw** [comment]
@eriksoderblom If Kodi states a preference, we should follow that. 256x256 is fine then.

Square sounds good. I think it looks better rounded outside of Kodi, but once it goes in, I agree that square will likely be better.

---Alex
