### ISSUE TITLE
Coaches Film doesn't work with Isengard

### ISSUE THREAD

**Issue by Alexqw** [Alexqw/xbmc-gamepass#177]
@eriksoderblom noted that Coaches Film doesn't seem to work with Isengard. And @BaumSchorle has foolishly volunteered to look into the problem. ;-)

Isengard didn't change/break too much compared to Helix, so hopefully it'll be an easy-ish fix.

**Comment by BaumSchorle** [comment]
@Alexqw I provided a fix for this, can you please check that everything works on Kodi 14.2?

Thanks.

**Comment by Alexqw** [comment]
@BaumSchorle It mostly works for me, but was quite laggy. But I've had some problems with GamePass's streams today, so it could just be the fault of streams taking awhile to load. It's good enough for now and I'll test it again later when their servers are a bit happier.

Thanks for looking into it. :-)

---Alex
