### ISSUE TITLE
Change addon type from plugin to script

### ISSUE THREAD

**Issue by BaumSchorle** [Alexqw/xbmc-gamepass#182]
I was looking for a solution for #133 because I am running into this issue at my installation, since I am using a shortcut.

After a lot of reading, I found out, that we are using a wrong addon type. As you can read in this document chapter 4: http://kodi.wiki/view/Python_Development

> 4 Python plugins versus scripts
Please do not confuse "Plugins" with "Scripts". Unlike the Scripts, Plugins are not meant to be directly invoked by the user. Instead, Plugins are automatically invoked when the user enters such a virtual folder. Do not try to run Plugins files from the scripts window as that will only give you a weird error message. Plugins, unlike Scripts, do not really provide new functionality to Kodi, instead what they do do is provide an easy way to present content listings in Kodi through the native GUI interface.

The thing is, that plugins are meant to have this 'folder structure' and we should have changed from plugin to script as we started with the GUI development.
I am wondering why the Kodi devs didn't mention this when they took us into the official repo.

I switched from plugin to script and the issue in #133 is immediately gone, when starting the addon from a shortcut on my homescreen.

**Comment by BaumSchorle** [comment]
Just to mention the change from plugin to script is really ease we just need to change to lines in our addon.xml:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<addon id="script.video.nfl.gamepass"
       name="NFL Game Pass"
       version="0.7.3"
       provider-name="Alexqw,divingmule,BaumSchorle,eriksoderblom">
  <requires>
    <import addon="xbmc.python" version="2.19.0"/>
    <import addon="script.module.xmltodict" version="0.9.0"/>
    <import addon="script.module.requests" version="2.4.3"/>
    <import addon="xbmc.gui" version="5.3.0"/>
  </requires>
  <extension point="xbmc.python.script" library="default.py">
    <provides>video</provides>
  </extension>
  <extension point="xbmc.addon.metadata">
    <summary lang="en">NFL Game Pass</summary>
    <description lang="en">Watch NFL Game Pass and NFL Game Rewind streams.</description>
    <platform>all</platform>
    <language>en</language>
    <license>GNU GENERAL PUBLIC LICENSE. Version 2, June 1991</license>
    <source>https://github.com/Alexqw/xbmc-gamepass</source>
    <forum></forum>
    <disclaimer lang="en">This addon requires you to have a subscription to either NFL Game Pass or NFL Game Rewind.[CR]Please note that these subscriptions are region restricted by the NFL.[CR]This addon is completely unofficial and is /not/ endorsed by the NFL in any way.</disclaimer>
  </extension>
</addon>
```

**Comment by Alexqw** [comment]
Nice catch.

Indeed, we should have made that change when switching to the skin approach. I say make the fix, and #133 will be properly resolved. :-)

As for the Kodi devs not mentioning anything, I lurked for awhile on that mailing list, and I never saw a rejection for code quality reasons (or any reason, for that matter). I think they don't have the time or energy to do review/QA. And to be honest, a lot of the addon code out there is horrible. Ours isn't too bad anymore (not stellar, but its ok), but in the early versions... **shudder**

---Alex

**Comment by Alexqw** [comment]
Wait... this might make things interesting to update to the new version. I ask on the addons mailing list if switching types will cause any problems.

**Comment by Alexqw** [comment]
@BaumSchorle Apparently, if we change the addon ID, then existing users will not automatically be upgraded to the new addon type.

Does this work if we only update the extension point? Or do both have to be updated for it to work properly?

If so, we can push out one last update to to the old plugin that includes a pop-up suggesting users uninstall/reinstall again.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw good new, changing the extension point is enough. No need to change the addon ID.
I will make the change and commit it to master and close this.

**Comment by Alexqw** [comment]
Awesome. Glad that there's no need to change the addon id. :-D

---Alex

**Comment by justinro** [comment]
Also posted on #133:
I updated to the latest (2015.08.17 v0.7.4) and I still can't exit out of the Addon when using a shortcut (through Advanced Launcher to be precise). I did verify that my addons.XML file has the updated code:

I'm using the CCM Helix skin if that matters, and exiting out of the plugin when entering through the Video Addons folder works fine.

Here's the Log if needed:
http://pastebin.com/raw.php?i=0ar6XEkA
