### ISSUE TITLE
InsecurePlatformWarning: urllib3 error with < Python 2.7.9

### ISSUE THREAD

**Issue by kaptain79** [Alexqw/xbmc-gamepass#183]
Im trying to get this to work for the first time with the plugin.  I can login to the nfl webpage just fine with a pc, but the plugin tells me that loggin into gamepass has failed, check your information.  So i have uninstalled gamepass and reinstalled it from the repository.  Still no go.
Here's my log file
http://sprunge.us/RQNW

Any ideas on what to try next?

**Comment by Jesia** [comment]
Did you try to login with your username instead of the email?

**Comment by chovy** [comment]
I was having this problem. I re-installed Isengard and it worked. I still can't play streams though.

**Comment by kaptain79** [comment]
No luck with username either, but it works with my laptop on the webpage...

**Comment by Alexqw** [comment]
@kaptain79 This looks like the same SSL issue we're seeing elsewhere. It checks if it's logged in, and it notes it's not. It tries to login, but it's redirected and urllib3 is unhappy about the encrypted redirect without proper support from Python. Thus the login process doesn't really happen, and then it checks again if its logged in (which it's not).

I should have some time today to test out an idea I have to fix this.

---Alex

**Comment by Alexqw** [comment]
So, I have something I'd like someone to try. Please note, this is not a real fix, at all.

The reason why urllib3 is angry is because it doesn't have the features needed from python in order to verify that the SSL certificate is from who it thinks its from. SSL provides encryption but also authentication of the identity of whom you're communicating with. So without verifying the identity of the cert holder, your data is encrypted, but you're not positive with whom you're communicating with.

urllib3 (sanely) errors in this scenario.

So, with that background, I would like you to try disable that warning so it succeeds anyway. This will not be the final fix, but it'll help me see in the logs what happens next.

Please edit resources/lib/pigskin.py and add the following lines after "import xmltodict" (line 14)

    import urllib3                                                                   
    urllib3.disable_warnings()

Do the usual dance of deleting your ~/.kodi/temp file and restarting kodi.

Then try to to use the addon, and provide a debug log.

Thanks!

---Alex

**Comment by kaptain79** [comment]
Im willing to try this where do I find pigskin.py?  
And do I delete kodi.log before restarting kodi?

**Comment by Alexqw** [comment]
`pigskin.py` is in the resources/lib folder of the addon (like it's at `~/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py`).

`kodi.log` is in the `~/.kodi/temp/` folder. Please delete the entire folder because it contains cached cookies, etc.

---Alex

**Comment by kaptain79** [comment]
Im getting script error when trying to load gamepass

3:42:49 T:140402121164544 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.viewtvjunkiemod/-poster.jpg
13:42:49 T:140402121164544 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.viewtvjunkiemod/-poster.png
13:42:49 T:140402121164544 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.viewtvjunkiemod/-banner.jpg
13:42:49 T:140402121164544 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.viewtvjunkiemod/-banner.png
13:42:49 T:140402121164544  NOTICE: Thread JobWorker start, auto delete: true
13:42:52 T:140402104321792  NOTICE: Thread LanguageInvoker start, auto delete: false
13:42:52 T:140402104321792  NOTICE: -->Python Interpreter Initialized<--
13:42:52 T:140402104321792   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named urllib3
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 16, in <module>
                                                from resources.lib.pigskin import pigskin
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 16, in <module>
                                                import urllib3
                                            ImportError: No module named urllib3
                                            -->End of Python script error report<--
13:42:52 T:140403481425792   ERROR: GetDirectory - Error getting plugin://plugin.video.nfl.gamepass/
13:42:52 T:140403481425792   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nfl.gamepass/) failed
13:42:52 T:140402104321792  NOTICE: Thread BackgroundLoader start, auto delete: false
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-poster.jpg
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-poster.png
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-banner.jpg
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-banner.png
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.jpg
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.jpg
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/?content_type=video-fanart.png
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.navi-x/fanart.png
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.view/-poster.jpg
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.view/-poster.png
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.view/-banner.jpg
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.view/-banner.png
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.viewtvjunkiemod/-poster.jpg
13:42:52 T:140402104321792 WARNING: CreateLoader - unsupported protocol(script) in script://script.hdhomerun.viewtvjunkiemod/-poster.png
13:42:52 T:140402104321792 W

**Comment by Alexqw** [comment]
Ahh shoot. That's my fault. It's looking for a systemwide urllib3, not Requests' copy of it.

Please use the following one line (instead of the two I had you use before)

    requests.packages.urllib3.disable_warnings()

**Comment by kaptain79** [comment]
here is the new log.  Still doesnt like the login information

http://sprunge.us/WfVF

**Comment by Alexqw** [comment]
@kaptain79 Ok. That apparently, literally, only disables the warning, and doesn't turn off verification.

I noticed you're not using the latest code. Can you update to the most recent master?

There's a "download .zip" on the right side of the main page.

---Alex

**Comment by Alexqw** [comment]
If I'm correct, everyone who has reported this problem so far is using OpenELEC. I'm currently talking with their devs to get a version bump from 2.7.3 to 2.7.10. Previous attempts (back in January) were reverted, but the reasoning is (as of yet) unknown.

I have an untested PR open (https://github.com/OpenELEC/OpenELEC.tv/pull/4279), but I think it's a bigger problem than a simpler one liner. Hopefully at very least, it'll start the discussion.

---Alex

**Comment by kaptain79** [comment]
I fixed my problem by changing my vpn port number, this should not have fixed it because the default port it didnt effect my laptop.  I dont know what gives, but it works now.

**Comment by Alexqw** [comment]
@kaptain79 Glad to hear it's resolved. I thought you were/are using Game Pass Domestic. So I'm surprised you're using a VPN...

Also, as an aside, please make sure that you're commenting in this thread and not the OpenELEC thread. It's on topic here, and spam over there.

So, the core part of this bug won't go away, but I'm thinking @dahlSTROM's servlet login patch (8a09652be47a843574c55f0a025b7f168219c674) prevented the redirect, which is the event that triggers this bug on platforms which are affected.

I'm still considering adding a catch for this error so it'll raise a dialog. But I don't think we should do anything fancier than that. And then just encourage people to upgrade. OpenELEC seems to have a patchset that works with Python 2.7.10. Hopefully they'll merge that soon. :-)

---Alex

**Comment by Alexqw** [comment]
As an update, the Python bump will not make it into OpenELEC 6.0. However, it will be included in the popular Millhouse builds. After a month or two of testing, if all looks good, it will likely be merged into OpenELEC.

---Alex

**Comment by crackulator** [comment]
@Alexqw, so is there a workaround, perhaps a patch we can apply to OpenELEC? We're running out of time here :)

**Comment by Alexqw** [comment]
@crackulator This problem is unfortunately a system python issue rather than an addon issue.

However, we've avoided the redirect, so normal operation doesn't have any redirects, and thus doesn't exhibit the behavior. Proxy, etc users might run into this problem, but that depends on what their provider is doing to their traffic.

I'm told that OpenELEC users can use the Millhouse build, which should include the Python 2.7.10 PR. Eventually that PR will be merged into OpenELEC, but that is up to them, and sounds like it will be a few months until they're comfortable with its stability.

---Alex

**Comment by wingrunr21** [comment]
FYI, I'm seeing this issue on Windows 8.1. Trying to find where/how Python is pulled into the Windows version to see if a version bump will help.

**Comment by Alexqw** [comment]
@wingrunr21 Kodi bundles its own version of Python. So that's where it's coming from. I'm told that updating it would be a non-trivial task, but it needs to be done at some point by someone. If you're interested in being that someone, you'd make a lot of people very happy. :-)

I thought we had gotten rid of all of the redirects. Would you mind turning on debugging and attaching a log? Are you using Game Pass Domestic or International?

---Alex

**Comment by Alexqw** [comment]
According to https://github.com/xbmc/xbmc/pull/8207 Python won't be bumped across-the-board for Jarvis. We can still hope for Kodi K***

However, https://github.com/OpenELEC/OpenELEC.tv/pull/4361 was merged into OpenELEC. I don't know what release it will belong to, but it's in. :-)

---Alex

**Comment by Alexqw** [comment]
The Python bump has been merged into Kodi Krypton. As there's nothing more we can do about this bug, and it's not really our fault, I'm going to close this.

---Alex
