### ISSUE TITLE
Remove Game Rewind from Skin

### ISSUE THREAD

**Issue by Alexqw** [Alexqw/xbmc-gamepass#186]
Now that Game Rewind is decommissioned, it should be removed from the skin.

It would be great to continue to visually differentiate between the Game Pass International and Game Pass Domestic services. If it's easy, the logo in the upper left should read "Game Pass Domestic", or something along those lines.

@eriksoderblom Would you be willing to take a stab at this if you have the time?

---Alex

**Comment by eriksoderblom** [comment]
@Alexqw I can remove Game Rewind later tonight.

But, do we have any way to tell if the user is international or in the US?
Is there somethings in the response from the servers?
We need that to be able to have the functionality you want in the skin.

**Comment by Alexqw** [comment]
@eriksoderblom We do have a way to tell if the user is domestic or now, but it's not coded yet. Maybe later in the week I'll have the time. I have a big upgrade project at work on Wednesday.

---Alex

**Comment by eriksoderblom** [comment]
@Alexqw Should i put the removal of Rewind in the same pull request as the domestic/international code or do you want separate?

**Comment by Alexqw** [comment]
@eriksoderblom whatever makes most sense to you. I'm not picky. :-)

**Comment by Alexqw** [comment]
@eriksoderblom Thanks a lot!

---Alex
