### ISSUE TITLE
Top 100 of 2015 - 0.7.4

### ISSUE THREAD

**Issue by t7504** [Alexqw/xbmc-gamepass#189]
FYI - the Top 100 of 2015 is not working in release 0.7.4.  Older seasons work ok.

**Comment by Alexqw** [comment]
@t7504 I /think/ that's because they havn't done the show yet for the best players of 2015. The code we're using 257 is correct. And we /are/ gettign a response from the Game Pass servers. It just says there's no episodes for Top 100 Players (2015)

    <?xml version="1.0" encoding="UTF-8"?>
    <result>
        <paging>
            <pageNumber>1</pageNumber>
            <totalPages>0</totalPages>
            <count>0</count>
        </paging>
        <id>257</id>
        <name>Top 100 Players (2015)</name>
        <breadCrumb>
            <item id="0"></item>
            <item id="1"><![CDATA[NFL]]></item>
            <item id="225"><![CDATA[Season 2015]]></item>
            <item id="257"><![CDATA[Top 100 Players (2015)]]></item>
        </breadCrumb>
        <programs>
        </programs>
    </result>

**Comment by frostyon420** [comment]
they haven't released them on the servers then. that Show has been over for like 2 months. you can go nfl's website to see what order the players were ranked

**Comment by t7504** [comment]
Looks like you are correct.  They don’t work on the NFL app either.  They aired in May, but must not have hit the servers yet.

**Comment by Alexqw** [comment]
@t7504 Then I'm going to close this for now. I think we're doing everything right. If/when the NFL app does have access and we don't, then please feel free to reopen. But I think it'll all just work out once GamePass fixes the problem.

---Alex
