### ISSUE TITLE
Gamepass Does not play some/most games

### ISSUE THREAD

**Issue by senguendk** [Alexqw/xbmc-gamepass#191]
I am having trouble with this addon (git master and 0.7.4 from kodi repository) as it does not seem to play most game at the moment.
Reproduce:
* Open Gamepass addon
* Select Gamepass > 201* > any game
* Chose any quality
* Video does not play

Expected:
Videos should play normally as it always has in the past.

Log (debugging active):
http://pastebin.com/WiPQ08m6

System:
* FireTV
* Kodi 15.1

Other information:
* Android app and viewing from browser works fine on the same network
* Problem appeared suddenly without prior problems or having made changes

**Comment by kaileu** [comment]
Did you try diffrent games or the seahawks chiefs game only?

The Problem with this game is that the game was in dvr mode and as far as i saw this won't work. Now this game is in archive mode so this should work now.

A little Background:
The games need some time to go from dvr mode (game inclusive commercial) into archive mode (without commercial) so this needs some time.
As an example the Seahawk game needed 12 hours!

Mit freundlichen Grüßen
KaiLeu

**Comment by senguendk** [comment]
Yes, I tried a whole bunch of other games from different season and different weeks. The only one working right now are the first two games in pre-season week 2.

**Comment by BaumSchorle** [comment]
I am facing the same issue, with yesterdays games. Everything else is working. 
This two games do not work on the windows app also, so this may be a GamePass issue.

**Comment by OakTwo** [comment]
Same issue for me... OpenElec and Add-on version 0.7.4 on a RaspberryPi B; there were issues playing Week 2 games before whereas Week 1 is fine, now just starting the Add-On causes the OpenElec to reboot.

Highlights from the error log are on http://pastebin.com/Ds1TMAPc

Seahawks versus Chiefs plays on my Chromebook OK, well, the first few seconds anyway... as you say on here, the interface isn't the best, so I couldn't watch it for long ;)

**Comment by kaileu** [comment]
Its a realy strange behaviour....
If i tunnel kodi through a transparent(no ip change nor data change) proxy to watch the traffic between kodi and the nfl Servers the streams working.....
If i shutdown the proxy the streams not working :-(
Really wierd. The Windows App has the same Problems only android and ios didn't have these kind of problems.

Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment]
I'm seeing the same issue with the Seahawks and Chiefs game. Bills and Browns work for me.

I tried most of the games from Preseason Week 1, and they all worked except Chiefs at Cardinals and Broncos at Seahawks.

I think that's interesting that it is again Chiefs and Seahawks games...

@BaumSchorle The Windows App issues do make me hope that this is a Game Pass issue.

Though, if this is a dvr issue as @kaileu thinks it is, we'll have to start sniffing again to figure out what magic sauce GP wants.

---Alex

**Comment by nignev** [comment]
At the moment the Dolphins vs Panthers game isn't working. I assume it's also the mode it's in as kaileu mentioned - dvr or archive, etc.

Some of the earlier games for Pre Week games such as Lions vs Redskins work fine.

**Comment by senguendk** [comment]
I just tried to watch any game from last night and none of them work unfortunately.

**Comment by BaumSchorle** [comment]
I just merged the fix from @kaileu which should fix this issue. Please download the latest master and test again!

**Comment by senguendk** [comment]
That was crazy fast. Thank you very much! It works perfectly thus far.

**Comment by nignev** [comment]
That's great thanks!
When will it come as an automated update? I'd rather not install it from here since I have to then upgrade manually from here as I understand?

**Comment by OakTwo** [comment]
Impressed at the speed of the fix.

Just a note for anyone reading this report who's on OpenElec on a Raspberry Pi B like me, neither manually updating the code by downloading the latest master zip file, or manually "patching" pigskin.py appeared to make a difference, save your time ;)  ( Or if you do make it work, contact me directly and tell me how... )

**Comment by BaumSchorle** [comment]
@OakTwo this is strange, it is working fine for me.
Please submit a log with the debuging turned on in the addon settings

**Comment by BaumSchorle** [comment]
@nignev if you replace the pigskin.py in the addons folder you should have no problem with future automatic updates

**Comment by kaileu** [comment]
@OakTwo did you restart the addon after you changed the file?

**Comment by Alexqw** [comment]
@nignev I will probably cut a new release at the end of the week (Thursday or Friday). I have some fixes/cleanup I want to get in this week, and I don't like spamming the kodi devs with releases, otherwise they get cranky. ;-)

---Alex

**Comment by nignev** [comment]
Thanks @BaumSchorle this worked.

@Alexqw no worries I got it working by replacing that file. Thanks for your work!

**Comment by Alexqw** [comment]
Closing, as this seems to be resolved now.

@nignev All the credit goes to @kaileu. :-)

---Alex
