### ISSUE TITLE
Cannot sign into GamePass today (worked fine last night)

### ISSUE THREAD

**Issue by jph55** [Alexqw/xbmc-gamepass#194]
I signed up for the 7 day trial and it worked fine last night, but today it is giving me username/password issues and won't login at all.  Logging in through the NFL website shows all the games and everything I could see last night in Kodi and the Add-On, so it is not a username/password issue.

Setup:
Amazon FireTV (not working), Win10 desktop (not working): both have Kodi 15.0 and GamePass Add-On 0.7.4.

I have a debug file for the Win10 machine, here's a link:  https://onedrive.live.com/redir?resid=DC4EA88281980F68!103395&authkey=!ABcfDrYzHkdPd8o&ithint=file%2clog

Thanks for any help!
Jason

**Comment by jph55** [comment]
Actually, here is a link to the debug file: https://onedrive.live.com/redir?resid=DC4EA88281980F68!103395&authkey=!ABcfDrYzHkdPd8o&ithint=file%2clog

**Comment by Alexqw** [comment]
@jph55 The log you provided didn't have the addon's debugging turned on, but, I'm pretty sure this is the same as #183 

To verify, can you turn on debugging in the addon and submit the log?

---Alex

**Comment by Setzer1994** [comment]
I'm having the same issue.  Win10, Kodi 14.2, GP addon 0.7.4 (fresh install)

14:37:43 T:1212   ERROR: C:\Users\Christopher\AppData\Roaming\Kodi\addons\script.module.requests\lib\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

**Comment by jph55** [comment]
I read through #183 and not sure what the final outcome was.  If it is a Python issue, how can I fix that on the Amazon Fire TV?  Like I said in the OP, it worked great last night watching multiple games and logging in and out on numerous occasions.

**Comment by kaileu** [comment]
Did you use any kind of vpn or proxy?

Mit freundlichen Grüßen
KaiLeu

**Comment by jph55** [comment]
Yes, OpenVPN through my router.  Exact same setup as last night.

**Comment by Alexqw** [comment]
@jph55 There is no real resolution yet to #183. It's not something that can be fixed in the addon (though we can catch the error, and provide a more informative message).

The fix is that the Python used by Kodi needs to be version 2.7.9 or greater.

Do you run OpenELEC on the Amazon Fire?

---Alex

**Comment by jph55** [comment]
No, just installed it from the repository (and from the GIT site today) and run it under Video-->Add-Ons-->.

**Comment by Alexqw** [comment]
@jph55 Sorry, I meant the OS for the KindleFire. Are you using the stock OS shipped by Amazon, or something else you installed on it?

**Comment by Alexqw** [comment]
@Setzer1994 Are you also using Game Pass Domestic?
The update for 0.7.4 finally hit the kodi addon servers a night or two ago. This could be a regression from 0.7.1 to 0.7.4. Odd, because we changed the login server, specifically to avoid this issue for Domestic users...

**Comment by Setzer1994** [comment]
@Alexqw 

Nope, overseas VPN.  Tried rolling back to 0.7.1, didn't work.  Reinstalled 0.7.4 fresh and didn't work either.  Thanks for the help, add-on (and gamepass in general) makes cordcutting easy!

**Comment by jph55** [comment]
Overseas VPN as well, and stock (up to date) FireTV OS.

**Comment by jph55** [comment]
Completely removed all traces of GamePass Add-On from Kodi and any config files (C:\users\Jason\AppData\Roaming\Kodi\Addons and C:\users\Jason\AppData\Roaming\Kodi\userdata\addon_data).
Connected to Belguim through my VPN
Reinstalled from the Kodi repository and entered my NFL account info...
and all is working again!
Also fully removed Add-On from FireTV and all config files, and it is working too!
Not sure why, but connecting to VPN before installing seemed to help, or it's just coincidence, but I removed and reinstalled about 5 times before trying with the VPN connected.
The debug log still shows a Python insecurity issue, but now says "loginsuccess" right after that.

Here's a copy of the debug log of the working add-on: http://1drv.ms/1hBKtnD

**Comment by Setzer1994** [comment]
Tried @jph55 solution and I also got it to work - 
1. Uninstalled addon
2. Deleted \Kodi\userdata\addon_data\plugin.video.nfl.gamepass\
3. Launched VPN connection
4. Reinstalled addon
5. Profit

**Comment by jph55** [comment]
Nice!
I played around a little more and tried to open it without being connected to VPN and it broke again, even when I reconnected to VPN.  Reinstalled and all is good again.
So, the moral is, don't even think about opening the GamePass Add-On without being connected to VPN first!

**Comment by kaileu** [comment]
It sounds like you want to use a gamepass europe subscription to login from inside us.
This would probably not work. I think even if they has the same names and login addresses they are diffrent in the backend.
And i think this is the real Problem of this issue and isn't realy a openelec problem. Can anybody test it from europe without vpns? 


Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment]
Both @BaumSchorle and I live in Europe. Everything works perfectly fine for us.

This is an issue caused by using VPN. It might be related to #183, which is resolved by using a platform that provides a newer version of Python, but no guarantees.

In any case, I am closing this bug, as we don't support circumventing Game Pass's region restrictions, and this bug seems to be specific to that situation.

---Alex
