### ISSUE TITLE
Stream issue

### ISSUE THREAD

**Issue by ewanm1** [Alexqw/xbmc-gamepass#197]
Firstly, thank you for a great app, I love it!

Been having an issue the last few days with Game Pass that's driving me spare. I can only watch 2015 Preseason week 1 games and the first 2 games of Preseason week 2. Every other game fails to load in Kodi 15.1 on Windows or on RaspBMC. NFL Network is unaffected. I think this is the relevant part of the log.

22:01:30 T:4580 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.jpg
22:01:30 T:4580 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.png
22:01:30 T:4580 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.jpg
22:01:30 T:4580 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.png
22:01:31 T:852  NOTICE: Thread JobWorker start, auto delete: true
22:01:31 T:5904  NOTICE: Thread LanguageInvoker start, auto delete: false
22:01:32 T:5904  NOTICE: -->Python Interpreter Initialized<--
22:01:35 T:2556  NOTICE: Thread JobWorker start, auto delete: true
22:01:46 T:2876  NOTICE: Previous line repeats 1 times.
22:01:46 T:2876  NOTICE: Thread GUIDialogCache start, auto delete: true
22:01:46 T:5356  NOTICE: DVDPlayer: Opening: http://nlds84.cdnak.neulion.com/nlds_vod/nfl/vod/2015/08/21/56778/1_56778_atl_nyj_2015_h_whole_1_3000.mp4.m3u8?nltid=nflgp&nltdt=6&nltnt=1&uid=804878&hdnea=expires%3D1440536619%7Eaccess%3D%2Fnlds_vod%2Fnfl%2Fvod%2F2015%2F08%2F21%2F56778%2F*%7Emd5%3D59945afe4746da185268518a21aec9e9|Connection=keep-alive&Cookie=nlqptid%3Dnltid%3Dnflgp%26nltdt%3D6%26nltnt%3D1%26uid%3D804878%26hdnea%3Dexpires%253D1440536619%257Eaccess%253D%252Fnlds_vod%252Fnfl%252Fvod%252F2015%252F08%252F21%252F56778%252F%2A%257Emd5%253D59945afe4746da185268518a21aec9e9&Accept-encoding=identity
22:01:46 T:5356 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
22:01:46 T:1200  NOTICE: Thread DVDPlayer start, auto delete: false
22:01:46 T:1200  NOTICE: Creating InputStream
22:01:46 T:2540  NOTICE: Thread FileCache start, auto delete: false
22:01:46 T:1200  NOTICE: Creating Demuxer
22:02:16 T:1200   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
22:02:16 T:1200  NOTICE: CDVDPlayer::OnExit()
22:02:16 T:5356  NOTICE: CDVDPlayer::CloseFile()
22:02:16 T:5356  NOTICE: DVDPlayer: waiting for threads to exit
22:02:16 T:5356  NOTICE: DVDPlayer: finished waiting
22:02:16 T:5356  NOTICE: CDVDPlayer::CloseFile()

**Comment by ewanm1** [comment]
Ah fixed it on the Windows box by uninstalling the kodi repo version and DLing from github.

Thanks again for a top app, now I can watch my beloved Broncos again :D

**Comment by Alexqw** [comment]
@ewanm1 Glad it worked out for you. :-)

Marking this as a duplicate of #191
