### ISSUE TITLE
Week 2 Pre-season games 2015 not working

### ISSUE THREAD

**Issue by jjduguay** [Alexqw/xbmc-gamepass#200]
Hello, I have a valid Game Pass subscription in Canada. I tested w the 7 trial and week 1 games worked fine. Now that I have paid for the account all but 1 of Week 2 games do not work. I am using the latest version of Kodi and Game Pass. Strange that week 1 games still work fine but Week 2 games won't open except the Lions Redskins game. Help please.

**Comment by kaileu** [comment]
Install the github version ;-)
Download as zip install is in Kodi and it should work ;-)

Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment]
@jjduguay As @kaileu mentioned, this issue has already been fixed (#191) in latest master. Or, you can wait a day or two, and the 0.8.0 release (which contains the fix) should hit Kodi's addon repo (I submitted it yesterday).

---Alex
