### ISSUE TITLE
NFL Network stops live streaming after a few minutes  back  2 

### ISSUE THREAD

**Issue by Yaya7** [Alexqw/xbmc-gamepass#201]
He  I keep watching  nfl network  but in few min 5 10 min  stopping 

in the log giving 

http://nlsk.neulion.com/nlsk1/hls/securekey?id=21&url=/n
lds/nfl/nfltv/as/live/nfltv_hd_2400/20150830165000.m3u8.key

**Comment by kaileu** [comment]
Did you use the current master?
And please provide a full log with debug information. This line you posted didn't help.

Mit freundlichen Grüßen
KaiLeu

**Comment by Yaya7** [comment]
yes  Im Uninstall Kodi and installed it again but some prob 

I have Prob like this  
https://github.com/Alexqw/xbmc-gamepass/issues/128

**Comment by Yaya7** [comment]
The prob  fixed it was ffmpeg  issue thnx

**Comment by Alexqw** [comment]
Glad it works for you. :-)
