### ISSUE TITLE
Archive Stream Drops Out - No new data packet received

### ISSUE THREAD

**Issue by jmoore626** [Alexqw/xbmc-gamepass#203]
Running latest stable Openelec Generic.

Games will play for 2-10 mins and then stop.

Get the following in the log:
22:09:47 T:140375499982592 WARNING: CDVDMessageQueue(video)::Get - asked for new data packet, with nothing available

Running latest master 0.8.0

Pastebin link below.

Please let me know what I can do on my end to help debug this issue.

http://pastebin.com/e2CXfkes

**Comment by Alexqw** [comment]
@jmoore626 Thanks for the bug report and the log. However, it doesn't look like you have debugging enabled. Can you provide a log with debugging enabled for both Kodi and the addon?

---Alex

**Comment by jmoore626** [comment]
@Alexqw I'll see what I can do but similarly to #164 it appears that app debug does not work on my openelec 5.0.8 system, which is based on Kodi 14.2

**Comment by Alexqw** [comment]
@jmoore626 If you can't enable debugging, then your system/Kodi install has some bigger problems going on.
Also worth noting, with OpenELEC, you might also run into bug #183 

---Alex

**Comment by Alexqw** [comment]
@jmoore626 I'm closing this for now, as there seems to be other problems with your system rather than just the addon. If you're still experiencing this problem once the other problems are resolved, feel free to reopen this issue. :-)

---Alex
