### ISSUE TITLE
NFLGamepass 0.8.0 - Games not loading

### ISSUE THREAD

**Issue by ppwibaux** [Alexqw/xbmc-gamepass#204]
Hello,

Im running Kodi 15.1 on Windows with audio pathtrough. 
Using NFLGamepass 0.8.0 from Kodi Repo (Also tried with the version from GitHub (a few minutes ago))

game were playing without problem (full or condensed) for pre-season week 1.
Then some week2 games were not loading (like the trouble other people had). 
I updated the addon, uninstall/reinstall multiple times from Kodi repo or GitHub, clear Cache, tried to copy/paste the pigskin.py ... 

Since then : no games are loading (even week 1 games)

I select the Game, select Full or Condensed, then the loading screen appears for 20to30 second, and i'm back to the game list.

Please find the kodi.log :
http://pastebin.com/r36eN5c2

Hope you'll find the solution :)
if you need any other information, feel free to ask ;)

Thanks !

**Comment by Alexqw** [comment]
@ppwibaux That's a bit odd that you're seeing this problem with the latest code. You said you modified your pigskin.py file, and now games no longer work. My bets guess is you edited something in a way that broke it. I recommend completely deleting your copy of the addon, deleting the entire `.kodi/temp` folder (to remove any caches), and starting fresh.

---Alex

**Comment by ppwibaux** [comment]
I did try to modify the pigskin.py at some point, as suggested someone in another poll. I installed fresh a few times since. both from Kodi repo or from here.

i'll try with deleting the .kodi/temp and let you know.

Thanks

Pph

**Comment by ppwibaux** [comment]
No changes with cache cleared.

here's another log : 
http://pastebin.com/4Ag9LYrj

thanks.

PPh

**Comment by Alexqw** [comment]
@ppwibaux NFL Network Live works, but not the games? That's... bizarre. They're nearly identical. I looked through the log. It looks sane to me.

I have two ideas, but I don't think either are terribly likely to be correct. 1) I noticed you're using 32bit Windows 7. It could be you're running into an uncommon Python/Kodi bug on that platform. 2) Your log indicates that you're using TV Addons, which provides addons outside of the Kodi repository. Some of those addons are specifically not allowed into the Kodi repo precisely because they /do/ conflict with other addons and create problems. I would recommend to remove that repo and all plugins installed from it.

Otherwise, I'm pretty much out of ideas. If you continue digging into this, feel free to ask questions.

---Alex

**Comment by ppwibaux** [comment]
@Alexqw to be sure, i made a new install of Kodi.

kodi is in 32bits but windows is 64bits
I only installed the skin Artic Zephir and the gamepass from Kodi Repo. still not working :/

I hope you'll find something else ;)

pph

**Comment by Alexqw** [comment]
@ppwibaux I am fresh out of ideas. At this point, you're in the driver's seat; you'll have to provide some info or ideas that we can help you with, because from this viewpoint (other than the symptom) everything /looks/ like it's working correctly.

---Alex

**Comment by ppwibaux** [comment]
@Alexqw, from what I can read in the logs, there is a Warning followed by an error after opening the stream:

19:15:02 T:2120  NOTICE: DVDPlayer: Opening: http://nlds84.cdnak.neulion.com/nlds_vod/nfl/vod/2015/09/13/56512/2_56512_det_sd_2015_h_snap2w_1_4500.mp4.m3u8?nltid=nflgp&nltdt=6&nltnt=1&uid=584487&hdnea=expires%3D1442337431%7Eaccess%3D%2Fnlds_vod%2Fnfl%2Fvod%2F2015%2F09%2F13%2F56512%2F*%7Emd5%3D31d673934f84c1e87507a613c13ae281|Connection=keep-alive&Cookie=nlqptid%3Dnltid%3Dnflgp%26nltdt%3D6%26nltnt%3D1%26uid%3D584487%26hdnea%3Dexpires%253D1442337431%257Eaccess%253D%252Fnlds_vod%252Fnfl%252Fvod%252F2015%252F09%252F13%252F56512%252F%2A%257Emd5%253D31d673934f84c1e87507a613c13ae281&Accept-encoding=identity%2C+gzip%2C+deflate&User-Agent=Safari%2F537.36+Mozilla%2F5.0+AppleWebKit%2F537.36+Chrome%2F31.0.1650.57
19:15:02 T:2120 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
19:15:02 T:2028  NOTICE: Thread DVDPlayer start, auto delete: false
19:15:02 T:2028  NOTICE: Creating InputStream
19:15:02 T:2944  NOTICE: Thread FileCache start, auto delete: false
19:15:02 T:2028  NOTICE: Creating Demuxer
19:15:32 T:2028   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
19:15:32 T:2028  NOTICE: CDVDPlayer::OnExit()
19:15:32 T:2120  NOTICE: CDVDPlayer::CloseFile()

I tried to google the error, but couldn't link the results to my case. Some people said it could be caused by mmpeg, but apart from VLC installed on that PC, i don't have any decoder installed (or i'm confusing ^^) 

Apart from that, could it be due to Artic:Zephir skin ? but it did work with this skin before all the stream started to fail. and I actualy need this skin because of its compatibility with Plex.

Maybe I could bypass the NFL addon with a shortcut that run the NFLgamepass webpage from the MainPage of Kodi ... but i'd prefer to get the addon working ;)

**Comment by Alexqw** [comment]
@ppwibaux `ffmpeg` is bundled with Kodi, so it won't be using the copy shipped with VLC. I agree the problem is that ffmpeg struggles to play the stream, but the question is *why*. And for that, I do not have an answer. *Especially* since NFL Network plays just fine; it makes little sense. The stream info returned for the games looks sane, so I don't know what the glitch is.

**Comment by ppwibaux** [comment]
2014 and prior games can play full or condensed.
but still no 2015 games. 

is there something that defers from this year's game and the one before ?

**Comment by kaileu** [comment]
The diffrence between this and last season is that the current Season requires an compressed request. Why  that didn't work with your client i can't tell because we send the Header with current version.

Mit freundlichen Grüßen
KaiLeu

**Comment by ppwibaux** [comment]
@kaileu I tested your modification of the pigskin.py from another poll before opening that topic.
if I remember well, it was this line 238
 
m3u8_header = {'Cookie': 'nlqptid=' + m3u8_param, 'User-Agent': 'Safari/537.36 Mozilla/5.0 AppleWebKit/537.36 Chrome/31.0.1650.57', 'Accept-encoding': 'identity, gzip, deflate'

but this didn't work :/

could it be another "user-agent" detected from Kodi on windows, that leads to line 245 (streams['only available'] = m3u8_url) and therfore not being able to be uncompressed ?

**Comment by kaileu** [comment]
No.
The Problem is we can't see the request and the answers  correctly....
You can try install proxifier and use the evaluation mode to tunnel the traffic from kodi to another Programm called Charles Web Proxy (also trial version) and record all traffic and save the file. But this isn't as easy as it sounds 😁.


Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment]
@ppwibaux If you are indeed running the latest code, line 238 should already contain that 'Accept Encoding'. So you are sending mixed signals to us. Was that line already there or not?

If not, please update to the latest version.

---Alex

**Comment by ppwibaux** [comment]
Here's the line I have in the pigtail.py

        m3u8_header = {'Cookie': 'nlqptid=' + m3u8_param, 'User-Agent': 'Safari/537.36 Mozilla/5.0 AppleWebKit/537.36 Chrome/31.0.1650.57', 'Accept-encoding': 'identity, gzip, deflate', 'Connection': 'keep-alive'}

**Comment by Alexqw** [comment]
@ppwibaux Have you updated to the latest release? Everything should be working now.

---Alex

**Comment by Alexqw** [comment]
Closing, as this /should/ be resolved and there's been no response.

@ppwibaux If this is still a problem with the latest code, please feel free to reopen this issue and we'll continue helping you with it.

---Alex
