### ISSUE TITLE
Logging failed

### ISSUE THREAD

**Issue by brutus** [Alexqw/xbmc-gamepass#205]
I just created a 7 day trial account on `gamepass.nfl.com`. It works well in my browser.

Then I installed this add-on trough the official repo (OSMC running on a rasberry pi), configured it (same credentials I use in my browser), but I get an error message on start:

> "ERROR Logging into NFL Game Pass failed. Make sure that…"

Does a trial account doesn't work with this add-on? 
Or are there additional steps needed? 

Any hints on how the solve / debug this are appreciated.

**Comment by brutus** [comment]
Solved the issue: the password must not be longer than 12 characters.

While longer passwords work fine in the browser, they cause errors on the android app and also this one.

**Comment by Alexqw** [comment]
@brutus Odd. My password is longer than 12 characters and I don't have problems. I know some services do this (AOL was famous back in the day for this). If we can figure out if/when it's doing this, we can easily truncate the password when we send it.

In any case, thanks for the bug report. :-)

---Alex
