### ISSUE TITLE
Trying to play blacked out games causes error

### ISSUE THREAD

**Issue by nworbneb** [Alexqw/xbmc-gamepass#207]
I get the bad jujumagumbo error when I try and play a blacked-out game.

If I use the iPad app it tells me which games are blacked out in the UK.  Perhaps the plugin can do similar?

Log file:

17:42:44 T:140445606725376  NOTICE: [pigskin]: Request URL: http://gamepass.nfl.com/nflgp/servlets/publishpoint
17:42:44 T:140445606725376  NOTICE: [pigskin]: Headers: {'User-Agent': 'iPad'}
17:42:44 T:140445606725376  NOTICE: [pigskin]: Response code: 400
17:42:44 T:140445606725376  NOTICE: [pigskin]: Response: <html><head><title>Apache Tomcat/6.0.36 - Error report</title><style></style> </head><body><h1>HTTP Status 400 - </h1><HR size="1" noshade="noshade"><p><b>type</b> Status report</p><p><b>message</b> <u></u></p><p><b>description</b> <u>The request sent by the client was syntactically incorrect.</u></p><HR size="1" noshade="noshade"><h3>Apache Tomcat/6.0.36</h3></body></html>
17:42:44 T:140445606725376  NOTICE: [plugin.video.nfl.gamepass-0.8.0]: Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/default.py", line 482, in onClick
                                                game_streams = gpr.get_publishpoint_streams(game_id, 'game', game_version)
                                              File "/storage/.kodi/addons/plugin.video.nfl.gamepass/resources/lib/pigskin.py", line 230, in get_publishpoint_streams
                                                m3u8_dict = xmltodict.parse(m3u8_data)['result']
                                              File "/storage/.kodi/addons/script.module.xmltodict/lib/xmltodict.py", line 248, in parse
                                                parser.Parse(xml_input, True)
                                            ExpatError: mismatched tag: line 1, column 956

**Comment by Alexqw** [comment]
@nworbneb Yeah, we have/had that feature, but they changed their blackout page, hence why it broke. Can you provide the full log with debugging enabled?

---Alex

**Comment by nworbneb** [comment]
Sorry had to wait for games to black out again.  Log here: http://pastebin.com/ZDC7mQE4

Please let me know if you need any more info.

**Comment by kaileu** [comment]
A better example is the log file of eth0 
http://pastebin.com/MF33BRsk

In the /servlets/games request you get the code <blocked>.


Mit freundlichen Grüßen
KaiLeu

**Comment by Alexqw** [comment]
@kaileu This should be relatively straightforward to fix. Though it's a bit different than the old GameRewind method of blackouts. It looks like you can login to Game Pass, but now each game is blocked. This means the code will need ot be refactored a bit, but it shouldn't be too bad.

I won't be able to work on this until next week at the earliest. My mother-in-law is visiting, and thus my free time is... limited.

If anyone else is interested in taking a stab at this before then, please feel free. :-)

---Alex

**Comment by BaumSchorle** [comment]
This should be fixed with my latest commit, can someone test this based in the UK?

Thanks.

@Alexqw sorry, didn't want to close it ;-)

**Comment by Alexqw** [comment]
@BaumSchorle No worries. I'm glad you're looking into this. I keep meaning to, but whenever I looked at the code, the issue kept sprawling. 

I /think/ the error we can raise at login (and all associated code) can be removed as well, because GamePass now allows logins during blackout, it just doesn't allow streams.

Are you adding anything to the UI to notify the user it's blacked out?

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw yep, a celanup on the old GameRewind code would be good. Maybe I find some time to look into this.

At the moment I was just focused to get rid of the 'bad jujumagumbo' error, and if I am correct with this fix the blacked out games should be just greyed out in the UI as if the have not started. So the user should see that they are marked as Live but they are greyed out.

I am not really good at skinning, but if anyone wants to add a special flag or something it can be done with the new ListItem propertie.

**Comment by Alexqw** [comment]
@BaumSchorle Or just update the gameinfo text with "Blacked Out" or "Blocked". That would be enough. Suppress playback with the "diabled" method you're doing, and then provide some informative text.

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw good point, I changed the game info text from 'Live' to 'Blacked Out'

**Comment by Alexqw** [comment]
@BaumSchorle Rock. :-)

---Alex

**Comment by nworbneb** [comment]
Thanks guys.  But I'm using OpenELEC which is based on Isengard and there isn't even a beta available with Jarvis.  The latest master forces xbmc.gui as 5.10.0 which kills this add on for most people, certainly everyone on OpenELEC.

**Comment by nworbneb** [comment]
So I frigged the xbmc.gui requirement to 5.9.0 running Isengard but I get gui corruption for the non-blacked out games (see linked jpg).  Not sure if this is a bug or if this is the mismatch in my hopelessly outdated kodi ;)
![nfl_gamepass](https://cloud.githubusercontent.com/assets/14279100/11596371/a14de2aa-9aac-11e5-97d1-351c413f9ebd.JPG)

**Comment by Alexqw** [comment]
@nworbneb I thought the popular [Milhouse builds](http://milhouse.openelec.tv/builds/master/) were running Jarvis. And if that's not an option, then we do have an isengard branch that you can install from. The last few patches aren't pushed to it yet, but when I'm next at my dev box I can refresh the branch.

---Alex

**Comment by Alexqw** [comment]
@nworbneb Ahh... that graphical glitch isn't a problem with Isengard. It's just that the game time info has a line break in it, so we're overlapping the info. I /really/ need to cleanup this area of the code, because the current setup makes it too easy to introduce bugs like this.

It's an easy fix though. Either @BaumSchorle can fix it, or I'll look at it when I'm next at my dev box.

---Alex

**Comment by nworbneb** [comment]
Thanks guys.  Let me know when you've got an update and I'll keep an eye on what it's doing pre/during/post blackout and when the games are available after the blackout.

**Comment by kaileu** [comment]
Correct me but Jarvis isn't a stable release? So most of the Player still using isengard.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment]
@kaileu Correct, Jarvis is currently in Beta 2, and will be released as stable "soon". The 0.9.0 (Jarvis) and 0.8.1(Helix/Isengard) releases are identical except for the xbmc.gui dependency. I intentionally bumped to 0.9.0 for Jarvis, so that there's version space on to 0.8.x line for continued Isengard updates --- if needed.

---Alex

**Comment by Alexqw** [comment]
@nworbneb @kaileu I just refreshed both the isengard and font-hack branches. They should be up-to-date with master.

---Alex

**Comment by Alexqw** [comment]
I think this bug was fixed by BaumSchorle quite the while ago.

Closing.

---Alex
