### ISSUE TITLE
Nfl Redzone

### ISSUE THREAD

**Issue by sportshd** [Alexqw/xbmc-gamepass#212]
I'm not seeing the option for redzone. All I see is

Gamepass. NFLNetwork. Along the top.

If I click on game pass I see the games bu t no redzone. If I click on NFL network then the option to see the NFL network comes up but nothing regarding redzone.

I've tried on a mac and pc

**Comment by Alexqw** [comment]
Closing. As this is a duplicate,

Please don't open duplicate issues. You know better.

---Alex
