### ISSUE TITLE
login credentials used to work but don't work anymore

### ISSUE THREAD

**Issue by xavierzinn** [Alexqw/xbmc-gamepass#214]
i am running 2 systems with kodi 15.1 git:d496682 (complied: aug 16 2015) on ubuntu 14.04.3 LTS (kernel 3.16.0-49) NFL Gamepass was working mint for weeks. i typed in my credentials and it just worked. Today i had to rebuild one of the systems and when i setup gamepass it told me my credentials were wrong and check if i have a valid subscription.

it wouldn't work, but on the other system it did work. i removed my username and pass on the working system and re-added them. Same problem check credentials and check if i have a valid subscription. the user and pass are correct because i can login to the gamepass website, and the NFL Gamepass app on my phone with those very credentials. 

i will be in front of another kodi box running windows 7 and i will see if it gives me the same issue and will update accordingly

**Comment by chovy** [comment]
I have this problem on one machine, the fire tv stick/kodi is fine, but my mac kodi is not.

**Comment by Alexqw** [comment]
Someone mentioned in another bug report that Game Pass limited them to using only 12 characters for their password. I have not been able to reproduce this, but it might be worth trying.

Otherwise, you're going to have to do some debugging to figure out why this is happening, as none of the devs have been able to reproduce it.

---Alex

**Comment by chovy** [comment]
my pw is less than 12 chars and i just started having this issue on my mac. Can we determine if its a mac-only problem? FireTV stick works fine for me.

**Comment by v3crax** [comment]
If you are in the states, the problem could possibly be your DNS Service. I was using AFT and switched to Smart DNS and that problem was eliminated.

**Comment by dbowles1975** [comment]
I had the same issue as the OP. If you go into the plug-in folder and delete  "gp_cookie_file" it starts working. Maybe Alex could explain this file and why it would give a login error?

**Comment by Alexqw** [comment]
That's the file where the cookie for the session is stored. If you don't have that file, it will force a new authentication. If you're doing proxy/VPN stuff, then I could see that causing problems. But if you're not, then I see no reason for there to be any problems with the cookie file.

---Alex

**Comment by Alexqw** [comment]
@xavierzinn Is this still an issue? If so, and if you're not using a VPN, etc please provide a log. Otherwise I will close this issue.

---Alex

**Comment by xavierzinn** [comment]
it's weird, i didn't do anything and it started working again. i don't have
a reason, nothing in the environment changed, so i will chalk this up to an
anomaly.  you can close the issue. if it happens again i will post a log
and open an trouble ticket.

Thanks for the followup.



On Fri, Oct 9, 2015 at 11:10 AM, Alex Waite <notifications@github.com>
wrote:

> @xavierzinn <https://github.com/xavierzinn> Is this still an issue? If
> so, and if you're not using a VPN, etc please provide a log. Otherwise I
> will close this issue.
>
> ---Alex
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexqw/xbmc-gamepass/issues/214#issuecomment-146898625>
> .
>



-- 

Xavier Zinn
xavier.zinn@gmail.com

**Comment by Alexqw** [comment]
Thanks for letting me now!

---Alex
