### ISSUE TITLE
Works on firetv, but not on windows?

### ISSUE THREAD

**Issue by smoothlarryhughes** [Alexqw/xbmc-gamepass#215]
Any reason why the gamepass streams would load on the fire tv running kodi, but I Just installed the add on in windows kodi and the streams go to load (spinning circle in bottom right hand corner), but then nothing??

**Comment by Alexqw** [comment]
@smoothlarryhughes It should work. Please enable debugging in both Kodi and the addon, and then provide the log.

**Comment by BaumSchorle** [comment]
@smoothlarryhughes Haven't heard back from you, so I will close this! Feel free to reopen if you still encounter any problems.
