### ISSUE TITLE
Sound but no video

### ISSUE THREAD

**Issue by crazyq84** [Alexqw/xbmc-gamepass#216]
We just bought a new tv box and installed NFL game pass. The screen listing all the games is a little messed up but able to deal with that but when loading games we get a black screen that says buffering then we get sound of the game and no video just a black screen.

**Comment by Alexqw** [comment]
@crazyq84 You'll need to provide more information for us to be able to help you. First off, please enable debugging for both kodi and the addon. Then submit an addon log.

---Alex

**Comment by crazyq84** [comment]
I am technology literate but not savvy. Maybe you can help with how to do
do these things?

**Comment by crazyq84** [comment]
I have enabled debugging on both kodi and the app but not sure how to access the log

**Comment by tfaoro** [comment]
I'm experiencing a similar issue on a Matricom G-Box Q (Android). After selecting a game and bitrate, the sound starts and I see the 'm3u' URL at the bottom of the screen with a play icon, however no video appears; the screen just continues to show the game selection screen as the audio plays.

I should be able to get you logs a bit later today, just wanted to say I'm also experiencing a similar issue and it's not a one off.

**Comment by tfaoro** [comment]
So here's the relevant section of logs: https://gist.github.com/tfaoro/8ff54c695798ffd71002

Line 138 stuck out to me:
`21:58:08 T:1960727648   DEBUG: ffmpeg[74DE5460]: [h264] no picture`

Let me know if I can provide anything further to help.

**Comment by BaumSchorle** [comment]
This is strange, since the Plugin seems to do what it should. Can you please provide a full log?

**Comment by tfaoro** [comment]
This was everything, what else are you looking for?

>

-- 
Tony Faoro
Circumventures, LLC

T: 425 270 1337 x 2912 | F: 425 207 3000 | circumventures.com

**Comment by BaumSchorle** [comment]
@tfaoro Looks like you provided the log from the point you klicked play on a game. I don't see the information you get after you logged in.
Best would be to delete xbmc.log and then start the addon, select a week, play a game and provide the full xbmc.log file

**Comment by tfaoro** [comment]
Alright @BaumSchorle here's a more complete log: https://gist.github.com/tfaoro/c6910d3338bbda5a58b2

I removed some local server paths and sanitized my login/name but otherwise it's complete.

**Comment by tfaoro** [comment]
Hey @Alexqw @BaumSchorle, don't mean to be a pest but have you guys had a chance to check out the latest logs I've sent? It'd be great to be able to stream the game tonight...

**Comment by dahlSTROM** [comment]
This is an issue with your system and has nothing to do with the addon. Based on the logs, it looks like amcodec doesn't work properly with the H264 profile Game Pass uses. You can try disabling hardware acceleration, though I'm pretty sure that will introduce frame drops.

**Comment by tfaoro** [comment]
So @crazyq84 I was able to get things working on my system by disabling libstagefright and MediaCodec video hardware acceleration. On my system playback is 95% perfect, but I'm sure results will vary depending on your hardware.

Thanks @dahlstrom for the advice and all your great work on this add-on 👍

**Comment by Alexqw** [comment]
@tfaoro Glad to hear it worked for you. :-)

@dahlSTROM @BaumSchorle Thanks for looking into this.

Closing, as @crazyq84 hasn't responded to this issue in over a month, and @tfaoro's problem is resolved.

---Alex
