### ISSUE TITLE
Redzone

### ISSUE THREAD

**Issue by zmottie** [Alexqw/xbmc-gamepass#217]
I don't appear to have an option to play Redzone content. I just tried the latest build and still nothing. It works on my phone and computer but not from within Kodi so I assume it's not my subscription or location. 

Where is the menu to play it located? When I click NFL Network (where I assume it would be) the screen is blank with only the years (2011-2015) available for selection. 

I assume I'm just doing something wrong so no logs attached yet :)

Thanks!

**Comment by chovy** [comment]
Should be in the upper right just below the NFL Network link.

https://www.dropbox.com/s/ayr20o7678r4a05/Screenshot%202015-10-11%2011.41.34.png?dl=0

**Comment by zmottie** [comment]
Definitely missing that icon. 

https://www.dropbox.com/s/gzuelr4v7suus6c/photo%202015-10-11%2C%201%2026%2034%20pm.jpg?dl=0

**Comment by BaumSchorle** [comment]
Looks like you are located in the US and are not able to watch ANY live action with GamePass.

**Comment by zmottie** [comment]
Gotcha, didn't realize I was a geographic restriction. I'll turn off my DNS trickery since I'm definitely not in the US :) Only use it to avoid blackout games.

**Comment by BaumSchorle** [comment]
I will close this issue, since it is a regional problem.
