### ISSUE TITLE
Games won't load when using Unblock-Us

### ISSUE THREAD

**Issue by joleger** [Alexqw/xbmc-gamepass#218]
Hey Everyone,

I am not sure if this has been brought up before, (if it has I apologize).   

I am a Canadian and a "cord cutter" but I love NFL Football so I subscribe to GamePass.  I install this add-on and it is fantastic.  As a Packers fan, I usually watch the Packers game after the kids go to bed so the add-on mostly suits my needs.  However, I do enjoy watching the Thursday and Monday night games so I use Unblock-US DNS VPN in conjunction with GamePass.

I attempted to use this Add-On with Unblock-Us on my Kodibuntu box but was unsuccessful.  I set my DNS by creating a static IP address.  I verified that Unblock-Us's DNS values were in my resolve.conf.

I am not saying this is a bug with the add-on, but rather I am looking for help in hopefully resolving the issue.  

I am a software developer by trade but have very little experience with python and web development.  I took a quick look at pigskin.py and I noticed that when a http request is made the allow_redirects parameter is set to false.  Not sure if matters or not to Unblock-Us.
    "req = self.http_session.get(url, params=payload, headers=headers, allow_redirects=False)"

I am willing to help test any fix and or contribute to a solution in any way I can.

Thanks again for a great add-on.

Cheers

J.O.

**Comment by joleger** [comment]
Just an update.  I changed "allow_redirects=False" to "allow_redirects=True" and it seems to work.  I will do some testing for a couple weeks and let you know how it goes

**Comment by Alexqw** [comment]
@joleger We don't officially support setups which get around region restrictions. It's a self preservation thing. It's against the NFL's ToS, and we'd like to continue to exist as a project.

Redirects are currently disallowed in a heavy-handed attempt to get around a Python/SSL bug on some platforms. Hopefully we can remove it in a years or so.

Closing, for the above-mentioned reasons.

---Alex
