### ISSUE TITLE
Unable to Play any Games

### ISSUE THREAD

**Issue by justinro** [Alexqw/xbmc-gamepass#220]
I'm a GamePass International subscriber with Unblock.US, and have been using this plugin without an issue for a few years. This week when I try to play any games, I'm getting the 'Working...' and then nothing loads.

Here is the log file:
http://pastebin.com/raw.php?i=fuMN9670

and the error:
10:50:28 T:4948   ERROR: ffmpeg[1354]: Unable to open key file http://nlsk.neulion.com/nlsk1/hls/securekey?id=127&url=/nlds/nfl/panthers/as/live/panthers_hd_4500/20151108180000.m3u8.key
10:50:28 T:4948   DEBUG: ffmpeg[1354]: Using network protocols without global network initialization. Please use avformat_network_init(), this will become mandatory later.
10:50:28 T:4948   DEBUG: Previous line repeats 1 times.
10:50:28 T:4948   ERROR: ffmpeg[1354]: [hls,applehttp] Error when loading first segment 'http://nlds127.cdnak.neulion.com/nlds/nfl/panthers/as/live/panthers_hd_4500_20151108184850.ts'

**Comment by Alexqw** [comment]
@justinro Sorry to be johnny-raincloud, but we don't officially support setups which get around region restrictions. It's a self preservation thing. It's against the NFL's ToS, and we'd like to continue to exist as a project.

Closing.

---Alex
