### ISSUE TITLE
Kodi 16 - GUI compatibility issue

### ISSUE THREAD

**Issue by jasnn** [Alexqw/xbmc-gamepass#222]
Found out [here] (http://forum.kodi.tv/showthread.php?tid=249477), that Kodi 16 sets the minimum GUI version to 5.10.0. Since the 0.8.0 Gamepass addon currently depends on GUI 5.3.0, the addon won't show up in the repository for Kodi 16, and a manual install will fail. However, editing line 14 of addon.xml to [import addon="xbmc.gui" version="5.10.0"], allows Kodi 16.0 beta 2 to accept manually installing the addon, and so far, it seems to be working fine.

**Comment by Alexqw** [comment]
Fixed by #224

**Comment by Alexqw** [comment]
@jasnn Thanks for reporting this issue.

---Alex
