### ISSUE TITLE
Some bad jujumagumbo error on live games

### ISSUE THREAD

**Issue by HenioH** [Alexqw/xbmc-gamepass#223]
Hello
Whenever I attempt to launch any of the live games I get that "Some bad jujumagumbo" error. All previously aired games play perfectly. I am running Kodi 15.2

Kodi.log: http://pastebin.com/syJWArZs

**Comment by BaumSchorle** [comment]
Hi,

looks like you are US based and therefore do not get any live games.

Raffael
Am 29.11.2015 10:13 nachm. schrieb "HenioH" <notifications@github.com>:

**Comment by HenioH** [comment]
Just realized this now im running through a VPN and it works. Thank you for
the extremely quick response
