### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by sixshooterz** [Alexqw/xbmc-gamepass#228]
![untitled](https://cloud.githubusercontent.com/assets/12206020/12000513/daba1526-aa9d-11e5-8d79-c3a9166c52db.png)
Some addons offer the ability to Download videos/streams for playback at a later time.  Is it possible to add this as an option in the Game Pass plugin?

Thanks!

**Comment by Alexqw** [comment]
@sixshooterz In principle, this is possible, but we won't be adding this feature. I dislike a world where legal concerns trump all, especially for something as trivial as a football game, but that's the world we currently live in. The feature would encourage pirating, and that would eventually hurt this project with unwanted (and undeserved) legal attention.

That being said, saving streams certainly is possible (though you should read the ToS carefully to see if it's permitted). So if you have the motivation and appropriate Python know-how, the majority of pieces are there for you to put together and use for your own private, personal purposes.

Closing as wontfix, but thanks for the suggestion, and enjoy your holidays. :-)

---Alex
