### ISSUE TITLE
cant get the timeline show....

### ISSUE THREAD

**Issue by CraigMack69** [Alexqw/xbmc-gamepass#230]
specifically "a tale of two cities part 2" it always kicks an error. Can anyone else confirm that episode not playing. It could always be on the servers end.

**Comment by chovy** [comment]
how do you get to this stream in the interface?

**Comment by CraigMack69** [comment]
NFL Network ---> 2015 ---> The Timeline ---> A Tale of two cities Part 2

**Comment by BaumSchorle** [comment]
This stream doesn't work in the Android app either, so I assume it's a
problem on the GamePass servers!
Am 24.01.2016 11:37 vorm. schrieb "CraigMack69" <notifications@github.com>:

**Comment by kaileu** [comment]
This episode didn't work on Gamepass either so i think its a gamepass issue

**Comment by chovy** [comment]
> NFL Network ---> 2015 ---> The Timeline ---> A Tale of two cities Part 2

I don't have "The Timeline" under 2015.

**Comment by CraigMack69** [comment]
cuz u probably don't have the latest build. Upgrade and try again. Doesn't matter anyway as I got my answer.

**Comment by CraigMack69** [comment]
Re-opened the issue. It seems it being streamed from "live" stream  servers on gamepass. The first part of the episode is streamed from VOD servers. So there maybe a fix in knowing that.


timeline a tale of two cities part 2 

http://nlds21.cdnl3nl.neulion.com/nlds/nfl/nfltv/as/live/nfltv_hd_400/20160130/03/2050.....blah.blah.blah


timeline a tale of two cities part 1

http://nlds84.cdnak.neulion.com/nlds_vod/nfl/vod/2015/12/20/151220/2_151220_t1_nfltv_2013_h_quickpick1_1_4500.mp4/00/0004.mp4

**Comment by chovy** [comment]
try to brute force one or the other for the alternate and see if one
version will support both streams.

On Fri, Jan 29, 2016 at 7:40 PM, CraigMack69 <notifications@github.com>
wrote:

> Re-opened the issue. It seems it being streamed from "live" stream servers
> on gamepass. The first part of the episode is streamed from VOD servers. So
> there maybe a fix in knowing that.
>
> timeline a tale of two cities part 2
>
>
> http://nlds21.cdnl3nl.neulion.com/nlds/nfl/nfltv/as/live/nfltv_hd_400/20160130/03/2050.....blah.blah.blah
>
> timeline a tale of two cities part 1
>
>
> http://nlds84.cdnak.neulion.com/nlds_vod/nfl/vod/2015/12/20/151220/2_151220_t1_nfltv_2013_h_quickpick1_1_4500.mp4/00/0004.mp4
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Alexqw/xbmc-gamepass/issues/230#issuecomment-177059375>
> .
>



-- 
Anthony Ettinger
http://about.me/anthony.ettinger

**Comment by CraigMack69** [comment]
nfl fixed. now closing for good
