### ISSUE TITLE
Show TV Network for a Given Game

### ISSUE THREAD

**Issue by Alexqw** [Alexqw/xbmc-gamepass#235]
Not sure if this info is in the returned XML. But if it is, it'd be nice to know which network a given game is broadcast on.

---Alex

**Comment by kaileu** [comment]
You mean if the stream ist broadcasted on Nbc ?

This Information isn't in the xml.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment]
I can't easily find this information anywhere in a nice maintained, tabular form. :'(

Closing.

---Alex
