### ISSUE TITLE
Gamepass List Section not working

### ISSUE THREAD

**Issue by HenioH** [Alexqw/xbmc-gamepass#237]
Hello,

Great addon been using it for a long time. As of today whenever I click on the Gamepass Section in the addon I get the "Some bad juju..." error. Haven't changed my login details as they are the same and the NFL Network Live link works perfect. Any help would be greatly appreciated.

**Comment by emilsvennesson** [comment]
#236...

**Comment by Alexqw** [comment]
@HenioH Thanks for the bug report. I'm closing this, as @emilsvennesson is correct that this is a duplicate. If there's anything we can do (short of waiting on the NFL to fix it), then bug #236 will be reopened.

---Alex
