### ISSUE TITLE
Can't load last season's games

### ISSUE THREAD

**Issue by amppyC** [Alexqw/xbmc-gamepass#241]
Hey guys, I really like the layout of the app and everything.  One thing I am having an issue though is loading last season's games.  When I click on NFL Gamepass International heading, I get the error check your logs message.  So I did and this is what I got:

19:18:24 T:9428  NOTICE: [plugin.video.nfl.gamepass-0.9.0]: script starting
19:18:24 T:9428 WARNING: CSkinInfo: failed to load skin settings
19:18:27 T:9428  NOTICE: [plugin.video.nfl.gamepass-0.9.0]: Traceback (most recent call last):
                                              File "C:\Users\****\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py", line 411, in onClick
                                                self.display_seasons_weeks()
                                              File "C:\Users\****\AppData\Roaming\Kodi\addons\plugin.video.nfl.gamepass\default.py", line 236, in display_seasons_weeks
                                                weeks = self.seasons_and_weeks[self.selected_season]
                                            KeyError: u'2016'
19:18:32 T:9428  NOTICE: [plugin.video.nfl.gamepass-0.9.0]: script finished

I'm guessing it's a simple fix or maybe last season's games are gone but just thought I'd ask.  I'm a total newb at this stuff. Thanks for all your hard work!

**Comment by kaileu** [comment]
I am guessing you are using the version from Kodi repository?
This version is broken at the moment.
You have to use the Git Version.
Duplicate from https://github.com/Alexqw/xbmc-gamepass/issues/236

Mit freundlichen Grüßen
Kai Leutner

**Comment by amppyC** [comment]
That did the trick, dude!  Thanks!

**Comment by Alexqw** [comment]
@BaumSchorle I'm going to cut a release today, because I've been getting quite a few bug reports like this. Thoughts on a release name?

---Alex

**Comment by BaumSchorle** [comment]
@Alexqw How about a Bart Starr Edition? :)

**Comment by Alexqw** [comment]
@BaumSchorle Nice. I dig. :-)

It shall be so.

---Alex

**Comment by Alexqw** [comment]
@amppyC I requested the new release be uploaded to the kodi repos. They usually update it within a day or two.

---Alex
