### ISSUE TITLE
Font obscuring game start time 

### ISSUE THREAD

**Issue by IANPARRY** [Alexqw/xbmc-gamepass#243]
Hi Guys

Just updated 0.9.1 and game start time is obscured (appears overlayed on Upcoming Game wording)Can this be fixed pls ?

Ps Thanks for the great work on this great add on
Ian

**Comment by Alexqw** [comment]
@IANPARRY thanks for the bug report.

This bug was fixed a few days ago in master. To resolve it, download and install the latest master, otherwise wait a few weeks for the next release. :-)

---Alex

**Comment by IANPARRY** [comment]
Great ! Many thanks Alex
