### ISSUE TITLE
No video on VU+ Solo2 (Enigma2)

### ISSUE THREAD

**Issue by ghost48** [Alexqw/xbmc-gamepass#244]
Just installed Kodi 16.1 RC2 on my VU+ Solo2 Sat Receiver (Enigma2 based).

With NFL Gamepass Version 0.9.1 and a valid Gamepass account I am unable to view any game. No sound and video is shown once I try to start an archived game or NFL Network Live.

Some specs shown in System Information
Free Space: 411 MB
Video solution: 1280x720@50 Hz
OpenGL Provider: Broadcom
OpenGL Version: OpenGL ES 2.0

I do not see any errors in the log but I will attach a kodi.log

[kodi.log.zip](https://github.com/Alexqw/xbmc-gamepass/files/402023/kodi.log.zip)

Let me know if you need further information. NFL season is around the corner. :-)

**Comment by Alexqw** [comment]
@ghost48 Super weird how your issue appeared out of nowhere. I never got a notification for it nor did I see it yesterday (but it's been open for 2 days). And with your handle... that's creepy. ;-)

You need to enable debugging for the log to be of any value. Please do so and upload a new one.

---Alex

**Comment by Alexqw** [comment]
Closing, as there's been no followup. @ghost48 Please feel free to reopen this if you're still experiencing the problem and are willing to provide a debug log.

---Alex
