### ISSUE TITLE
subcription

### ISSUE THREAD

**Issue by smalone78** [Alexqw/xbmc-gamepass#246]
hi, I have downloaded the gamepass 3x and everytime I go to open it it wants to make sure I have a subscription. do I need to pay $99 for the subscription to use or not? if not I need help with it. what do I do?

**Comment by kaileu** [comment]
Yes you need a valid subscription.

Mit freundlichen Grüßen
Kai Leutner

**Comment by smalone78** [comment]
is there something that I wouldn't need to pay for I just want to watch preseason games

**Comment by kaileu** [comment]
I am sorry.
This addon needs the same things as the original Accounts.
I am sorry :(

Mit freundlichen Grüßen
Kai Leutner

**Comment by BaumSchorle** [comment]
@smalone78 You need a valid subscription and we do not support any activities to get around the subscription, since we do not want the NFL to shut this addon down.

I will close this issue.
