### ISSUE TITLE
Constant buffering

### ISSUE THREAD

**Issue by SullyCT79** [Alexqw/xbmc-gamepass#249]
I'm running the latest build of the NFL Game Pass add-on with the latest Kodi 16.1 and it seems like no matter what I try, the video keeps buffering.  I have this setup on a Win 10 Surface Pro 3 and Fire TVs.  The Fire TVs are wired and the SP3 is wireless.  

I'm using Overplay SmartDNS using a Germany server.  I have tried modifying the acceleration renderer in Kodi to software.

Could it be the DNS service I'm using?

EDIT:  I have no problem using the official Game Pass website or mobile apps.  Log attached.
[kodi log.zip](https://github.com/Alexqw/xbmc-gamepass/files/410088/kodi.log.zip)

**Comment by Displayel** [comment]
its running great for me on whatever device, Nvida Shield TV, Fire TV, iPad..so it must be the DNS Server

**Comment by Alexqw** [comment]
@SullyCT79 I (and others) are having no problem with buffering. I suspect (though have not confirmed) that Game Pass attempts to give you a stream that is located near you on the network, but when you use a proxy it gives you a stream near the location of your proxy, and thus you're streaming across the Atlantic and are encountering congestion. Just a guess, but it'd make sense. We do tend to see much more buffering with proxy users.

As for having no problems with the Official App, perhaps they are doing more aggressive buffering, and the client is delaying you by a few seconds to help smooth out the stream. This would make sense, but I don't know of any way to have Kodi replicate this behavior.

---Alex

**Comment by SullyCT79** [comment]
While I was experiencing buffering I realized I was signed into my account on my web browser.  Once I signed out everything has been running smooth.  No buffering at all.  Closing the issue.

**Comment by Alexqw** [comment]
@SullyCT79 Glad to hear everything is working well. :-)
