### ISSUE TITLE
Use m3u8 from Kodi's repos; drop our bundled copy

### ISSUE THREAD

**Issue by Alexqw** [Alexqw/xbmc-gamepass#250]

**Comment by Alexqw** [comment]
As FYI, for everyone, when updating, make sure the resources/lib/m3u8/ folder is gone, otherwise you'll run into problems. Also, if you're not installing via Kodi's repos, you will need to install the m3u8 package from here: http://mirrors.kodi.tv/addons/jarvis/script.module.m3u8/

As this change has a higher chance than usual of causing user problems, I'm leaving this issue open for at least a few days --- as a place for troubleshooting and feedback.

---Alex

**Comment by Ghoschdi** [comment]
Unfortunately it does not work in the 17.A3, but i could not find an updated m3u8 for the 17.x branch, so this could be the problem

`21:33:03 T:9264   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named dateutil
                                            Traceback (most recent call last):`

Will test on the 16.x later today and report back.

**Comment by Alexqw** [comment]
@Ghoschdi What do you mean not updated for 17.x? It's in there repos here: http://mirrors.kodi.tv/addons/krypton/script.module.m3u8/

There's not quite enough in that traceback to see what's going on. Next time can you provide a more of the trace?

---Alex

**Comment by Ghoschdi** [comment]
@Alexqw : Yes, it is in the repos. I first tried to usual way of installing via zip and letting the repo fetch the module. This created the error above. Afterwards i pulled the module myself from the source and updated via zip, same error. 

`10:10:30 T:992   DEBUG: CPythonInvoker(1, C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass\default.py): instantiating addon using automatically obtained id of "plugin.video.nfl.gamepass" dependent on version 2.19.0 of the xbmc.python api
10:10:30 T:992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named dateutil
                                            Traceback (most recent call last):
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass\default.py", line 17, in <module>
                                                from resources.lib.pigskin import pigskin
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass\resources\lib\pigskin.py", line 8, in <module>
                                                import m3u8
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\__init__.py", line 22, in <module>
                                                from m3u8.model import M3U8, Playlist, IFramePlaylist, Media, Segment
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\model.py", line 7, in <module>
                                                import arrow
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\arrow\__init__.py", line 3, in <module>
                                                from .arrow import Arrow
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\arrow\arrow.py", line 11, in <module>
                                                from dateutil import tz as dateutil_tz
                                            ImportError: No module named dateutil
                                            -->End of Python script error report<--
10:10:30 T:992    INFO: Python script stopped
10:10:30 T:992   DEBUG: Thread LanguageInvoker 992 terminating`

**Comment by Alexqw** [comment]
@Ghoschdi Ok, so this version of m3u8 depends on something called arrow (which they remove in a later version). It itself depends on dateutil. I don't know why m3u8 doesn't declare that as a dep itself. Try either installing it via your system's package manager or install the Kodi version: http://mirrors.kodi.tv/addons/krypton/script.module.dateutil/

---Alex

**Comment by Ghoschdi** [comment]
@Alexqw: Good! I did not find that one from the package manager, so this is why i never looked it up. I pulled the zip, installed it, rebooted kodi, but same error. Repeated three times to make sure it works, but does not. Strange

`10:27:51 T:9356   DEBUG: CPythonInvoker(1, C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass\default.py): instantiating addon using automatically obtained id of "plugin.video.nfl.gamepass" dependent on version 2.19.0 of the xbmc.python api
10:27:51 T:9356   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named dateutil
                                            Traceback (most recent call last):
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass\default.py", line 17, in <module>
                                                from resources.lib.pigskin import pigskin
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass\resources\lib\pigskin.py", line 8, in <module>
                                                import m3u8
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\__init__.py", line 22, in <module>
                                                from m3u8.model import M3U8, Playlist, IFramePlaylist, Media, Segment
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\model.py", line 7, in <module>
                                                import arrow
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\arrow\__init__.py", line 3, in <module>
                                                from .arrow import Arrow
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\arrow\arrow.py", line 11, in <module>
                                                from dateutil import tz as dateutil_tz
                                            ImportError: No module named dateutil
                                            -->End of Python script error report<--
10:27:51 T:9356    INFO: Python script stopped
![screenshot 2016-08-11 10 29 28](https://cloud.githubusercontent.com/assets/10353742/17582917/855f7c08-5fae-11e6-9057-3cc017b4fa96.png)
`

**Comment by Alexqw** [comment]
@Ghoschdi That is.... just weird. I don't know why kodi isn't seeing dateutil as being in the path...

**Comment by Ghoschdi** [comment]
Maybe a hickup on my windows installation. Will try a complete fresh approach later and report back in the afternoon. Thanks for highlighting the direction :)

/Stefan

**Comment by Ghoschdi** [comment]
Tried again on fresh K17A3 - i manually installed dateutil, m3u8 and afterwards GP, same error...
Tried fresh 16.1 stable with same approach, same error
`15:28:41 T:2212   DEBUG: CPythonInvoker(1, C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass-master\default.py): instantiating addon using automatically obtained id of "plugin.video.nfl.gamepass" dependent on version 2.19.0 of the xbmc.python api
15:28:41 T:2212   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named dateutil
                                            Traceback (most recent call last):
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass-master\default.py", line 17, in <module>
                                                from resources.lib.pigskin import pigskin
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass-master\resources\lib\pigskin.py", line 8, in <module>
                                                import m3u8
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\__init__.py", line 22, in <module>
                                                from m3u8.model import M3U8, Playlist, IFramePlaylist, Media, Segment
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\model.py", line 7, in <module>
                                                import arrow
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\arrow\__init__.py", line 3, in <module>
                                                from .arrow import Arrow
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\arrow\arrow.py", line 11, in <module>
                                                from dateutil import tz as dateutil_tz
                                            ImportError: No module named dateutil
                                            -->End of Python script error report<--
15:28:41 T:2212    INFO: Python script stopped`

**Comment by Ghoschdi** [comment]
@Alexqw: Just curious - if the addon does not set deps, is there any way of letting Kodi fetch script modules from the repo instead of using the zip files.

**Comment by Alexqw** [comment]
@Ghoschdi Addons do declare their deps, they're just not read/honored when installing from zip (for whatever reason). When installing addons through the normal kodi interface, all the dependencies are taken care of for you.

---Alex

**Comment by Ghoschdi** [comment]
@Alexqw: Thanks, i know this, i just thought there is a way of getting modules from the repo, just like addons. Anyways, the error open is the same on 16.x and 17. with your latest master branch version and manually installing the dateutil module.

**Comment by Alexqw** [comment]
@Ghoschdi Let's try a different approach... Let's try the latest m3u8 code.  Can you download the four files from [this repo](https://github.com/globocom/m3u8/tree/master/m3u8) and use them to replace the appropriate files in your m3u8 addon folder? The arrow dir can be deleted in there also. If you see any .pyc or .pyo files, deleting those wouldn't hurt. And then restart Kodi.

The latest m3u8 code doesn't use arrow, which then shouldn't depend on dateutil, and just avoids this entire issue. If this works, then I'll ask the kodi devs about updating the m3u8 dep.

---Alex

**Comment by emilsvennesson** [comment]
@Alexqw Don't you have to import dateutil in addon.xml first? I don't think it'll try to load it otherwise even if it's installed.

**Comment by Ghoschdi** [comment]
@Alexqw:
fresh 16.x / 17.x installs (GP from ZIP, m3u8 is getting pulled automatically, replacing the m3u8 files with the linked version) now throws another missing module error
```
10:34:29 T:7152   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named iso8601
                                            Traceback (most recent call last):
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass-master\default.py", line 17, in <module>
                                                from resources.lib.pigskin import pigskin
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\xbmc-gamepass-master\resources\lib\pigskin.py", line 8, in <module>
                                                import m3u8
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\__init__.py", line 22, in <module>
                                                from m3u8.model import M3U8, Playlist, IFramePlaylist, Media, Segment
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\model.py", line 16, in <module>
                                                from m3u8 import parser
                                              File "C:\Users\stefa\AppData\Roaming\Kodi\addons\script.module.m3u8\lib\m3u8\parser.py", line 6, in <module>
                                                import iso8601
                                            ImportError: No module named iso8601
                                            -->End of Python script error report<--
```

So I went ahead and pulled down the Kodi m3u8 package, edited the addon.xml to reflect the requirement of dateutil
`<import addon="script.module.dateutil" version="2.4.2"/>` and it works now. 
So I see 3 solutions
A) we can use the new m3u8 and fix the ISO dep
B) Kodi team fixes their requirements for m3u8
C) GP adds the dateutil as a dep (kind of odd)

/Stefan

**Comment by Alexqw** [comment]
@ emilsvennesson We aren't using dateutil directly, it goes pigskin->m3u8->arrow->dateutil

So, m3u8 should be declaring dateutil as a dep (because it's bundling arrow, which has the dateutil dep). In any case, the addon.xml doesn't do the loading, it just declares the dependencies. The python import line is all that's needed to import. I really don't understand why dateutil isn't in kodi's python path for Ghoschdi.

---Alex

**Comment by Alexqw** [comment]
@Ghoschdi Interesting. I'm surprised. Maybe Kodi does something odd with parsing addon.xml deps and uses those to build the python path on a per-addon basis.... That doesn't sound right, but it seems to match the behavior you're seeing.

I lean towards solution B). I'll send an email to martijn sometime today or tomorrow.

---Alex

**Comment by Displayel** [comment]
can someone explain, what the issue could be if no update is done, i have kodi 16.1 installed on my nvidia shield with the latest 0.9.1 version manually installed and have absolutely no issues.

havent touched krypton A3 yet since A2 was to buggy for me with too many crashes, will wait for the final release of this.

i also saw that the official gamepass app for iPad was updated yesterday, they called it "important updates to get you ready for 2016 season" anyone knows what the "Important update" is ?

**Comment by kaileu** [comment]
The important update is the Logo of the LA Rams and i think a few  
minor bug fixes.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Ghoschdi** [comment]
@Displayel: I would not recommend to go for Krypton for daily usage. I am just testing the new release as it is much more convenient on Shield TV, which provides me a good way to report back any challenges with the current GP addon.

**Comment by Displayel** [comment]
does this have anything to do with the buffer issues i have today ? after not 1 yesterday today is kind of unwatchable no matter which game i try no matter if on nvidia shield or fire tv

**Comment by Ghoschdi** [comment]
@Displayel: Watched several live games tonight and had 0 buffering challenges. So might be an issue with your connectivity?

**Comment by Alexqw** [comment]
@Displayel These changes should have no impact on buffering. They should only affect the way we extract information from the m3u8 playlist and present those streams (and their information) to the user.

---Alex

**Comment by Alexqw** [comment]
For reference: https://github.com/timewasted/script.module.m3u8/issues/2

**Comment by emilsvennesson** [comment]
It seems like @timewasted is either busy or inactive. Maybe we should try sending a PR directly to https://github.com/xbmc/repo-scripts/pulls with the included dep fix? I can imagine this affecting quite a lot of other addons.

**Comment by Alexqw** [comment]
@emilsvennesson Yeah; I agree. Are you interested in doing that? I might not be able to get to that for a couple more days. It shouldn't be that hard, just takes a bit of time.

---Alex

**Comment by emilsvennesson** [comment]
@Alexqw Sure! Do you think we should bump the m3u8 version as well or just add the dateutil dependency? I can package iso8601 for Kodi if we'd like to use a newer version.

**Comment by Alexqw** [comment]
@emilsvennesson Awesome. A version bump is a good idea IMO. As far as I'm aware, there's no compatibility issues, so it should be low-risk.

However, that might take a bit longer, as I don't know how the Kodi devs handle a new maintainer taking over without explicit 'ok' from the old guy. You can find out though. ;-)

---Alex

**Comment by emilsvennesson** [comment]
Let's hope they're okay with it! https://github.com/xbmc/repo-scripts/pull/227

**Comment by emilsvennesson** [comment]
It's been merged now. :)

@Alexqw Just a reminder to make sure you update the m3u8 version requirement in addon.xml so people don't accidentally grab the bugged version. :wink:

**Comment by Ghoschdi** [comment]
@emilsvennesson: Good news. Pushed the version my Kodi 17.x repo and works like a charm. Thank you! :)

**Comment by Alexqw** [comment]
@emilsvennesson Thanks! Time for a 0.9.2 release :-)
