### ISSUE TITLE
Release 0.9.2

### ISSUE THREAD

**Issue by Alexqw** [Alexqw/xbmc-gamepass#259]
I'm thinking it's getting to be about that time... Before the end of the week.

@emilsvennesson Care to suggest a player/coach for a release name? :-)

**Comment by Ghoschdi** [comment]
Does this make sense knowing that the m3u8 change can break a lot of current installations, as they will miss the required dateutil?

**Comment by Alexqw** [comment]
@Ghoschdi I hope to have that resolved before making this release. I was just getting the ball rolling. :-)

---Alex

**Comment by emilsvennesson** [comment]
@Alexqw Sure thing! How about 'Jimmy Johnson Edition'? :grimacing:

**Comment by Alexqw** [comment]
@emilsvennesson Consider it so named. :-)

---Alex

**Comment by CraigMack69** [comment]
Nice one @emilsvennesson I named one of the releases "tom Landry edition" keep that cowboy spirit up :)

**Comment by Displayel** [comment]
so when i try to use the latest gamepass version from github i get an gamepass error check the log for errors....but when i use the one from kodi respitory...it works

**Comment by Alexqw** [comment]
@Displayel Ok. Did you, perhaps, check the log for errors? ;-)

That would help to figure out what's up. But would guess it's due to a missing dateutil dependency, which is currently what's holding up making this release.

---Alex

**Comment by Displayel** [comment]
Hi Alex, sorry its on SPMC on Fire TV the last time i had to make a log for you was a long time ago, cant remember how i did it :)

**Comment by Alexqw** [comment]
@Displayel http://kodi.wiki/view/Log_file

**Comment by Alexqw** [comment]
The release has been cut, and the PR is waiting to be merged for this to hit Kodi's repos. https://github.com/xbmc/repo-plugins/pull/636

---Alex
