### ISSUE TITLE
SPMC?

### ISSUE THREAD

**Issue by dbowles1975** [Alexqw/xbmc-gamepass#263]
Is there any reason that this add-on should not run in SPMC? I have tried to install it on a fresh SPMC install on two different Android devices and I'm getting an "Unexpected error. Please enable debugging..."

I can submit logs if needed. Thanks.

**Comment by chovy** [comment]
Please paste logs. 

- Anthony

**Comment by Displayel** [comment]
working for me on SPMC on a fire tv and nvidia shield...latest version from Koid repository
