### ISSUE TITLE
BUG? Unable to login with GP 0.9.1 

### ISSUE THREAD

**Issue by jsmootiz** [Alexqw/xbmc-gamepass#264]
I successfully used GP with unlocator last year on my firety. I just tried to get everything going for this year and I am unable to login. I simply get the unable to log in error (that I may have the wrong credentials). I am still using unlocator. My credentials are correct, and I am able to log in to my account and watch Game Pass content on my computer using a browser. However, all attempts to connect with GP 0.9.1 fails on both my FireTV and Mac computer. I am attaching the log file from my Mac computer attempt as it was easier to get the file and it contained that same errors that I viewed on my FireTV.  Any help would be greatly appreciated!

[Kodi_Log.docx](https://github.com/Alexqw/xbmc-gamepass/files/433921/Kodi_Log.docx)

**Comment by kaileu** [comment]
I am sorry but this error isn't related to our Addon.
The Bug is raised because of Unlocator which seems to be not  
compatible anymore.

Mit freundlichen Grüßen
Kai Leutner

**Comment by kaileu** [comment]
I am sorry but this error isn't related to our Addon.
The Bug is raised because of Unlocator which seems to be not compatible anymore.

Mit freundlichen Grüßen
Kai Leutner

**Comment by jsmootiz** [comment]
Thanks for looking at it. Are you aware of another service like unlocator that is compatible?

**Comment by kaileu** [comment]
No i am sorry.
Its against GamePass Policies so we are not allowed to help you sorry :(

Mit freundlichen Grüßen
Kai Leutner

**Comment by Alexqw** [comment]
@jsmootiz The problem you're experiencing is due to using a proxy. Furthermore, as @kaileu noted, we do not support proxies when used for the purpose of getting around Game Pass's region restrictions, as it is against their Terms of Service.

Closing this issue.

---Alex
