### ISSUE TITLE
NFL Network

### ISSUE THREAD

**Issue by wixmmm** [Alexqw/xbmc-gamepass#274]
Hi,

I am doing the free trial from NFL.com for game pass. The problem I'm having is that the replays work, but the 'NFL Network' half of the addon does nothing when I click it.

A couple days ago, the addon let me login as an international user and that did work and I could see all the NFL Network offerings. But then I had to do a 'fresh start' in kodi for other reasons and once i reinstalled the addon the international login was gone and the NFL Network half of the addon still does nothing.

Any help would be much appreciated, especially before saturday when my free trial ends.

Thanks,
Michael

**Comment by jm-duke** [comment]
Doing some clean-up and this issue report is really old, so I'm closing it.
