### ISSUE TITLE
Explore supporting 2009-2010 games

### ISSUE THREAD

**Issue by Alexqw** [Alexqw/xbmc-gamepass#36]
The new XML approach to getting seasons and week no longer provides info about 2009 and 2010. This is ok, though, since games pre 2012 didn't work anyway.

We should explore if there's any way to support these games. If not, tough luck, but it's worth examining.

**Comment by nexxai** [comment]
Any chance there's been movement on this?  Would love to get access to the 2009 games.

**Comment by Alexqw** [comment]
@nexxai I looked into it again briefly a few months ago, and had no luck. The streams are in a different format from the newer ones. Hopefully, someday the NFL will update those streams to HLS.

---Alex

**Comment by Alexqw** [comment]
Closing for now, as it seems these streams are stuck in a format we can't play. This issue will be reopened if the situation ever changes.

---Alex
