### ISSUE TITLE
Live games do not work.

### ISSUE THREAD

**Issue by Tuhwin** [Alexqw/xbmc-gamepass#384]
I got a legit game pass subscription, and using no proxies.
NFL Network live stream works.
Yesterday's games under GamePass International -> Preseason week 1 works.
Live games under GamePass International -> Preseason week 1 do not work. Was same during the HoF game last week.

Log included. I switched from NFL Network live which is working to try the Live Falcons vs Jets game under Gamepass International. Got a message about enabling debug, try again, and include log file in this bug report.

01:43:07.487 is when I closed NFL Network live and switched over to attempt starting the live game.
[kodi.log](https://github.com/aqw/xbmc-gamepass/files/2280243/kodi.log)

Is it on my end I've done something wrong, or is it simply so that the kodi plugin needs an update for this new season?

**Comment by CraigMack69** [comment]
Where are locted. Have you checked out the changes for EU and UK users. Different then it was last year. Int gamepass is for Latin America and I think Australia. Maybe some others

**Comment by Tuhwin** [comment]
Thanks for responding.
I'm not sure if you mean the subscription I took is wrong, or if I managed to get the wrong kodi gamepass version?

I'm located in Sweden. Got gamepass from NFL page as usual, and page was showing correct currency etc so I'm quite sure the subscription of PRO is the correct one for my location.

Is there 2 or more NFL Gamepass kodi apps out there?

**Comment by Tuhwin** [comment]
So, I've checked the main page of this kodi plugin/addon and I see that there's a distinction between GamePass Europe and the GamePass International.
I've tried my best to figure out which I got. The NFL GamePass page don't mention this anywhere that I could find. The only thing I can see there is that I have PRO pass. My location is Sweden as I stated before.

My reference to "GamePass International" is only from what I see when I start up the plugin/addon in Kodi. I've got two options in the main header menu. GamePass International and NFL Network. Is that "detection" based? Does it say "GamePass Europe" for other persons subscribing to GamePass in Europe, or is this Europe/International a legacy thing that was for 2017 and have been changed?

**Comment by kaileu** [comment]
This Addon is for Gamepass Europe only.
https://digitalcare.nfl.com/hc/en-us/articles/115009025268-Game-Pass-Europe

The Gamepass International has some restriction. There is a fork for Gamepass International but i have no idea what features are supported which not.

**Comment by Tuhwin** [comment]
Thank you for that info. Just curious though, is this due to live games are streamed from one source, and live NFL Network and archived things are streamed from another? Or why is it just Live Games that isn't working?

**Comment by kaileu** [comment]
As far as i know there is no live games for international Subscription.

**Comment by Tuhwin** [comment]
I just saw that too. My ONLY reference that points to me having an "International" subscription and not the Europe one, is in the actual kodi plugin/addon.

I'm pretty sure that's wrong. The registration and paying and all that on nfl.com took into account that I live in Sweden, which is a GamePass Europe country.

**Comment by kaileu** [comment]
I will take a look at this in a few days.

**Comment by Tuhwin** [comment]
Since Live Games is available to me through the website, we can then be sure I have a GamePass Europe subscription. It's basically the addon (from official kodi repo or straight from here as a .zip) that thinks I belong in the International group. Just want to be completely clear that it works on website during live games. Thanks for looking into it when you got the time.

Meanwhile I'll see if I can figure out where this check is in the code and modify into thinking it's a Europe version.

**Comment by kaileu** [comment]
@Tuhwin see my last post

**Comment by Tuhwin** [comment]
Gotcha. Will do that immediately. The first log I uploaded and was available for anyone to download for 24hrs, had my login info in it. I noticed the day after and uploaded a new one. Maybe that should be mentioned somewhere in the process.

Anyhow, I'll get on that immediately. 5mins.

**Comment by Tuhwin** [comment]
Crap, there's no live games right now, so impossible for me to trigger the error, just realized.

**Comment by rva87** [comment]
@Tuhwin please upload log if not working with the current code.

I'll submit a code update to prevent passwords from being logged

**Comment by Tuhwin** [comment]
Alright. Tried with the version I downloaded from here. No issues whatsoever.
Sorry for taking up your time with it. I had no idea the one in the official kodi addons repo was old.

Thank you for very quick responses and an awesome addon. Peace.
