### ISSUE TITLE
Support nlds53 streams (2011~2012 games, Super Bowl Archives, et al)

### ISSUE THREAD

**Issue by aqw** [Alexqw/xbmc-gamepass#66]
All streams from nlds53 currently don't work in XBMC. This affects:
- ~~All games for 2011~~
- ~~A few games in 2012~~
- ~~Super Bowl Archives~~
- Red Zone Archives from 2011 (see issue #96)
- All 2012 shows except Red Zone Archives and Total Access (see issue #96)
- ~~Top 100 Players for 2013~~

**Comment by torres3490** [comment]
I just spent an hour reading this and I still don't understand a fckn word it means. But im sure this is how nfl2go does it's streams
